/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityLogRouteImport } from './routes/activity-log'
import { Route as ClarificationsRouteImport } from './routes/clarifications'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ClosureTrackingRouteImport } from './routes/closure-tracking'
import { Route as DataRequirementsRouteImport } from './routes/data-requirements'
import { Route as EngagementsRouteImport } from './routes/engagements'
import { Route as EvidenceReviewRouteImport } from './routes/evidence-review'
import { Route as FinalReportingRouteImport } from './routes/final-reporting'
import { Route as ManagementActionsRouteImport } from './routes/management-actions'
import { Route as ManagementResponsesRouteImport } from './routes/management-responses'
import { Route as ObservationsRouteImport } from './routes/observations'
import { Route as ScopeProgrammeRouteImport } from './routes/scope-programme'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as EngagementsIndexRouteImport } from './routes/engagements.index'
import { Route as EngagementsEngagementIdRouteImport } from './routes/engagements.$engagementId'
import { Route as ScopeProgrammeIndexRouteImport } from './routes/scope-programme.index'
import { Route as ScopeProgrammeScopeIdRouteImport } from './routes/scope-programme.$scopeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogRoute = ActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ClarificationsRoute = ClarificationsRouteImport.update({
  id: '/clarifications',
  path: '/clarifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosureTrackingRoute = ClosureTrackingRouteImport.update({
  id: '/closure-tracking',
  path: '/closure-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRequirementsRoute = DataRequirementsRouteImport.update({
  id: '/data-requirements',
  path: '/data-requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementsRoute = EngagementsRouteImport.update({
  id: '/engagements',
  path: '/engagements',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceReviewRoute = EvidenceReviewRouteImport.update({
  id: '/evidence-review',
  path: '/evidence-review',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalReportingRoute = FinalReportingRouteImport.update({
  id: '/final-reporting',
  path: '/final-reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementActionsRoute = ManagementActionsRouteImport.update({
  id: '/management-actions',
  path: '/management-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementResponsesRoute = ManagementResponsesRouteImport.update({
  id: '/management-responses',
  path: '/management-responses',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservationsRoute = ObservationsRouteImport.update({
  id: '/observations',
  path: '/observations',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeProgrammeRoute = ScopeProgrammeRouteImport.update({
  id: '/scope-programme',
  path: '/scope-programme',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const EngagementsIndexRoute = EngagementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EngagementsRoute,
} as any)
const EngagementsEngagementIdRoute = EngagementsEngagementIdRouteImport.update({
  id: '/$engagementId',
  path: '/$engagementId',
  getParentRoute: () => EngagementsRoute,
} as any)
const ScopeProgrammeIndexRoute = ScopeProgrammeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScopeProgrammeRoute,
} as any)
const ScopeProgrammeScopeIdRoute = ScopeProgrammeScopeIdRouteImport.update({
  id: '/$scopeId',
  path: '/$scopeId',
  getParentRoute: () => ScopeProgrammeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-log': typeof ActivityLogRoute
  '/clarifications': typeof ClarificationsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/closure-tracking': typeof ClosureTrackingRoute
  '/data-requirements': typeof DataRequirementsRoute
  '/engagements': typeof EngagementsRouteWithChildren
  '/evidence-review': typeof EvidenceReviewRoute
  '/final-reporting': typeof FinalReportingRoute
  '/management-actions': typeof ManagementActionsRoute
  '/management-responses': typeof ManagementResponsesRoute
  '/observations': typeof ObservationsRoute
  '/scope-programme': typeof ScopeProgrammeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/engagements/$engagementId': typeof EngagementsEngagementIdRoute
  '/scope-programme/$scopeId': typeof ScopeProgrammeScopeIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/engagements/': typeof EngagementsIndexRoute
  '/scope-programme/': typeof ScopeProgrammeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-log': typeof ActivityLogRoute
  '/clarifications': typeof ClarificationsRoute
  '/closure-tracking': typeof ClosureTrackingRoute
  '/data-requirements': typeof DataRequirementsRoute
  '/evidence-review': typeof EvidenceReviewRoute
  '/final-reporting': typeof FinalReportingRoute
  '/management-actions': typeof ManagementActionsRoute
  '/management-responses': typeof ManagementResponsesRoute
  '/observations': typeof ObservationsRoute
  '/settings': typeof SettingsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/engagements/$engagementId': typeof EngagementsEngagementIdRoute
  '/scope-programme/$scopeId': typeof ScopeProgrammeScopeIdRoute
  '/clients': typeof ClientsIndexRoute
  '/engagements': typeof EngagementsIndexRoute
  '/scope-programme': typeof ScopeProgrammeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-log': typeof ActivityLogRoute
  '/clarifications': typeof ClarificationsRoute
  '/clients': typeof ClientsRouteWithChildren
  '/closure-tracking': typeof ClosureTrackingRoute
  '/data-requirements': typeof DataRequirementsRoute
  '/engagements': typeof EngagementsRouteWithChildren
  '/evidence-review': typeof EvidenceReviewRoute
  '/final-reporting': typeof FinalReportingRoute
  '/management-actions': typeof ManagementActionsRoute
  '/management-responses': typeof ManagementResponsesRoute
  '/observations': typeof ObservationsRoute
  '/scope-programme': typeof ScopeProgrammeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/engagements/$engagementId': typeof EngagementsEngagementIdRoute
  '/scope-programme/$scopeId': typeof ScopeProgrammeScopeIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/engagements/': typeof EngagementsIndexRoute
  '/scope-programme/': typeof ScopeProgrammeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-log'
    | '/clarifications'
    | '/clients'
    | '/closure-tracking'
    | '/data-requirements'
    | '/engagements'
    | '/evidence-review'
    | '/final-reporting'
    | '/management-actions'
    | '/management-responses'
    | '/observations'
    | '/scope-programme'
    | '/settings'
    | '/clients/$clientId'
    | '/engagements/$engagementId'
    | '/scope-programme/$scopeId'
    | '/clients/'
    | '/engagements/'
    | '/scope-programme/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity-log'
    | '/clarifications'
    | '/closure-tracking'
    | '/data-requirements'
    | '/evidence-review'
    | '/final-reporting'
    | '/management-actions'
    | '/management-responses'
    | '/observations'
    | '/settings'
    | '/clients/$clientId'
    | '/engagements/$engagementId'
    | '/scope-programme/$scopeId'
    | '/clients'
    | '/engagements'
    | '/scope-programme'
  id:
    | '__root__'
    | '/'
    | '/activity-log'
    | '/clarifications'
    | '/clients'
    | '/closure-tracking'
    | '/data-requirements'
    | '/engagements'
    | '/evidence-review'
    | '/final-reporting'
    | '/management-actions'
    | '/management-responses'
    | '/observations'
    | '/scope-programme'
    | '/settings'
    | '/clients/$clientId'
    | '/engagements/$engagementId'
    | '/scope-programme/$scopeId'
    | '/clients/'
    | '/engagements/'
    | '/scope-programme/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityLogRoute: typeof ActivityLogRoute
  ClarificationsRoute: typeof ClarificationsRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  ClosureTrackingRoute: typeof ClosureTrackingRoute
  DataRequirementsRoute: typeof DataRequirementsRoute
  EngagementsRoute: typeof EngagementsRouteWithChildren
  EvidenceReviewRoute: typeof EvidenceReviewRoute
  FinalReportingRoute: typeof FinalReportingRoute
  ManagementActionsRoute: typeof ManagementActionsRoute
  ManagementResponsesRoute: typeof ManagementResponsesRoute
  ObservationsRoute: typeof ObservationsRoute
  ScopeProgrammeRoute: typeof ScopeProgrammeRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-log': {
      id: '/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof ActivityLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clarifications': {
      id: '/clarifications'
      path: '/clarifications'
      fullPath: '/clarifications'
      preLoaderRoute: typeof ClarificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closure-tracking': {
      id: '/closure-tracking'
      path: '/closure-tracking'
      fullPath: '/closure-tracking'
      preLoaderRoute: typeof ClosureTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-requirements': {
      id: '/data-requirements'
      path: '/data-requirements'
      fullPath: '/data-requirements'
      preLoaderRoute: typeof DataRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements': {
      id: '/engagements'
      path: '/engagements'
      fullPath: '/engagements'
      preLoaderRoute: typeof EngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence-review': {
      id: '/evidence-review'
      path: '/evidence-review'
      fullPath: '/evidence-review'
      preLoaderRoute: typeof EvidenceReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final-reporting': {
      id: '/final-reporting'
      path: '/final-reporting'
      fullPath: '/final-reporting'
      preLoaderRoute: typeof FinalReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-actions': {
      id: '/management-actions'
      path: '/management-actions'
      fullPath: '/management-actions'
      preLoaderRoute: typeof ManagementActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management-responses': {
      id: '/management-responses'
      path: '/management-responses'
      fullPath: '/management-responses'
      preLoaderRoute: typeof ManagementResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observations': {
      id: '/observations'
      path: '/observations'
      fullPath: '/observations'
      preLoaderRoute: typeof ObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope-programme': {
      id: '/scope-programme'
      path: '/scope-programme'
      fullPath: '/scope-programme'
      preLoaderRoute: typeof ScopeProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/engagements/': {
      id: '/engagements/'
      path: '/'
      fullPath: '/engagements/'
      preLoaderRoute: typeof EngagementsIndexRouteImport
      parentRoute: typeof EngagementsRoute
    }
    '/engagements/$engagementId': {
      id: '/engagements/$engagementId'
      path: '/$engagementId'
      fullPath: '/engagements/$engagementId'
      preLoaderRoute: typeof EngagementsEngagementIdRouteImport
      parentRoute: typeof EngagementsRoute
    }
    '/scope-programme/': {
      id: '/scope-programme/'
      path: '/'
      fullPath: '/scope-programme/'
      preLoaderRoute: typeof ScopeProgrammeIndexRouteImport
      parentRoute: typeof ScopeProgrammeRoute
    }
    '/scope-programme/$scopeId': {
      id: '/scope-programme/$scopeId'
      path: '/$scopeId'
      fullPath: '/scope-programme/$scopeId'
      preLoaderRoute: typeof ScopeProgrammeScopeIdRouteImport
      parentRoute: typeof ScopeProgrammeRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface EngagementsRouteChildren {
  EngagementsEngagementIdRoute: typeof EngagementsEngagementIdRoute
  EngagementsIndexRoute: typeof EngagementsIndexRoute
}

const EngagementsRouteChildren: EngagementsRouteChildren = {
  EngagementsEngagementIdRoute: EngagementsEngagementIdRoute,
  EngagementsIndexRoute: EngagementsIndexRoute,
}

const EngagementsRouteWithChildren = EngagementsRoute._addFileChildren(
  EngagementsRouteChildren,
)

interface ScopeProgrammeRouteChildren {
  ScopeProgrammeScopeIdRoute: typeof ScopeProgrammeScopeIdRoute
  ScopeProgrammeIndexRoute: typeof ScopeProgrammeIndexRoute
}

const ScopeProgrammeRouteChildren: ScopeProgrammeRouteChildren = {
  ScopeProgrammeScopeIdRoute: ScopeProgrammeScopeIdRoute,
  ScopeProgrammeIndexRoute: ScopeProgrammeIndexRoute,
}

const ScopeProgrammeRouteWithChildren = ScopeProgrammeRoute._addFileChildren(
  ScopeProgrammeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityLogRoute: ActivityLogRoute,
  ClarificationsRoute: ClarificationsRoute,
  ClientsRoute: ClientsRouteWithChildren,
  ClosureTrackingRoute: ClosureTrackingRoute,
  DataRequirementsRoute: DataRequirementsRoute,
  EngagementsRoute: EngagementsRouteWithChildren,
  EvidenceReviewRoute: EvidenceReviewRoute,
  FinalReportingRoute: FinalReportingRoute,
  ManagementActionsRoute: ManagementActionsRoute,
  ManagementResponsesRoute: ManagementResponsesRoute,
  ObservationsRoute: ObservationsRoute,
  ScopeProgrammeRoute: ScopeProgrammeRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
