import os
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from app.utils import num_to_words_indian
from app.database import get_database_dir

class NumberedCanvas(canvas.Canvas):
    """Canvas that performs a two-pass render to draw dynamic 'Page X of Y' footers."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#718096"))
        
        # Draw a line above footer
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(36, 45, 559, 45) # Margins of 36pt (width of A4 is 595.27pt)
        
        # Draw page info right-aligned
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(559, 30, page_text)
        
        # Draw software watermarking left-aligned
        self.drawString(36, 30, "Generated by Smart Billing Manager - GST Compliant Offline Billing")
        
        self.restoreState()


def generate_pdf(invoice_data, output_path):
    """Generates a professional GST tax invoice PDF using ReportLab."""
    # A4 dimensions: 595.27 x 841.89 points. Margins: 36pt. Printable width: 523.27pt.
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=54 # Space for footer
    )

    template_style = invoice_data.get("template_style", "Classic Elegant")
    
    # Theme configuration
    if template_style == "Modern Minimalist":
        primary_hex = "#0F766E" # Teal
        primary_color = colors.HexColor(primary_hex)
        secondary_bg = colors.HexColor("#F0FDFA") # Very light teal
        border_hex = "#E2E8F0"
        border_color = colors.HexColor(border_hex)
        font_base = 8.5
        font_table = 8.0
        padding_val = 6
        spacer_scale = 1.0
        table_grid_style = [
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('ALIGN', (0,0), (-1,0), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('LINEBELOW', (0,0), (-1,-2), 0.5, border_color),
            ('LINEBELOW', (0,-1), (-1,-1), 1.0, primary_color),
            ('TOPPADDING', (0,0), (-1,-1), padding_val),
            ('BOTTOMPADDING', (0,0), (-1,-1), padding_val),
        ]
    elif template_style == "Professional Compact":
        primary_hex = "#2C3E50" # Slate Grey
        primary_color = colors.HexColor(primary_hex)
        secondary_bg = colors.HexColor("#F8FAFC")
        border_hex = "#CBD5E1"
        border_color = colors.HexColor(border_hex)
        font_base = 7.5
        font_table = 7.0
        padding_val = 2.5
        spacer_scale = 0.5
        table_grid_style = [
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('ALIGN', (0,0), (-1,0), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('GRID', (0,0), (-1,-1), 0.5, border_color),
            ('TOPPADDING', (0,0), (-1,-1), padding_val),
            ('BOTTOMPADDING', (0,0), (-1,-1), padding_val),
        ]
    else: # Classic Elegant (Default)
        primary_hex = "#1A365D" # Navy Blue
        primary_color = colors.HexColor(primary_hex)
        secondary_bg = colors.HexColor("#F0F4F8") # Light blue-grey
        border_hex = "#CBD5E1"
        border_color = colors.HexColor(border_hex)
        font_base = 8.5
        font_table = 8.0
        padding_val = 5
        spacer_scale = 1.0
        table_grid_style = [
            ('BACKGROUND', (0,0), (-1,0), primary_color),
            ('ALIGN', (0,0), (-1,0), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('GRID', (0,0), (-1,-1), 0.5, border_color),
            ('TOPPADDING', (0,0), (-1,-1), padding_val),
            ('BOTTOMPADDING', (0,0), (-1,-1), padding_val),
        ]
        
    def make_spacer(w, h):
        return Spacer(w, h * spacer_scale)

    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=14 if template_style == "Professional Compact" else 18,
        leading=17 if template_style == "Professional Compact" else 22,
        textColor=primary_color,
        alignment=2 # Right aligned
    )
    
    body_style = ParagraphStyle(
        'InvoiceBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=font_base,
        leading=font_base + 2.5,
        textColor=colors.HexColor("#2D3748")
    )
    
    body_bold_style = ParagraphStyle(
        'InvoiceBodyBold',
        parent=body_style,
        fontName='Helvetica-Bold'
    )
    
    table_hdr_style = ParagraphStyle(
        'TableHdr',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=font_table,
        leading=font_table + 1.5,
        textColor=colors.white,
        alignment=1 # Center aligned
    )
    
    table_cell_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=font_table,
        leading=font_table + 2,
        textColor=colors.HexColor("#2D3748")
    )
    
    table_cell_right_style = ParagraphStyle(
        'TableCellRight',
        parent=table_cell_style,
        alignment=2 # Right aligned
    )
    
    table_cell_center_style = ParagraphStyle(
        'TableCellCenter',
        parent=table_cell_style,
        alignment=1 # Center aligned
    )
    
    table_cell_bold_right_style = ParagraphStyle(
        'TableCellBoldRight',
        parent=table_cell_right_style,
        fontName='Helvetica-Bold'
    )

    elements = []

    # 1. Header (Seller details on left, Title & Invoice Meta on right)
    seller = invoice_data.get("seller", {})
    invoice_number = invoice_data.get("invoice_number", "")
    invoice_date = invoice_data.get("date", "")
    place_of_supply = invoice_data.get("place_of_supply", "N/A")
    rcm_status = "YES" if invoice_data.get("rcm", False) else "NO"
    
    seller_details_html = f"""
    <b>{seller.get('trade_name', '')}</b><br/>
    {seller.get('address', '')}<br/>
    Mobile: {seller.get('mobile', '')} | Email: {seller.get('email', '')}<br/>
    GSTIN: <b>{seller.get('gstin', '')}</b>
    """
    
    # Check if a logo image exists in configured database path
    logo_path = os.path.join(get_database_dir(), "logo.png")
    logo_elem = None
    if os.path.exists(logo_path):
        from reportlab.platypus import Image
        try:
            # Scale logo
            logo_elem = Image(logo_path, width=1.4*inch, height=0.6*inch)
            logo_elem.hAlign = 'LEFT'
        except Exception:
            logo_elem = None

    if logo_elem:
        header_left_data = [[logo_elem], [Spacer(1, 4)], [Paragraph(seller_details_html, body_style)]]
        header_left_table = Table(header_left_data, colWidths=[260])
        header_left_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 1),
            ('TOPPADDING', (0,0), (-1,-1), 0),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
        ]))
        left_cell = header_left_table
    else:
        left_cell = Paragraph(seller_details_html, body_style)

    invoice_meta_html = f"""
    <font size="9.5"><b>INVOICE NO:</b> {invoice_number}</font><br/>
    <font size="9.5"><b>DATE:</b> {invoice_date}</font><br/>
    <font size="9"><b>PLACE OF SUPPLY:</b> {place_of_supply}</font><br/>
    <font size="9"><b>REVERSE CHARGE (RCM):</b> {rcm_status}</font>
    """
    
    header_data = [
        [left_cell, [Paragraph("TAX INVOICE", title_style), Spacer(1, 8), Paragraph(invoice_meta_html, ParagraphStyle('RightMeta', parent=body_style, alignment=2))]]
    ]
    
    header_table = Table(header_data, colWidths=[280, 240])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 0),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
    ]))
    elements.append(header_table)
    
    # Dynamic divider line
    divider_data = [['', '']]
    divider_table = Table(divider_data, colWidths=[420, 100])
    divider_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,0), primary_color),
        ('BACKGROUND', (1,0), (1,0), colors.HexColor("#9B2C2C")),
        ('BOTTOMPADDING', (0,0), (-1,-1), 3),
        ('TOPPADDING', (0,0), (-1,-1), 0),
    ]))
    elements.append(divider_table)
    elements.append(make_spacer(1, 12))

    # 2. Customer billing details & Ship-to details side-by-side if specified
    customer = invoice_data.get("customer", {})
    ship_to = invoice_data.get("ship_to", {})
    
    cust_details_html = f"""
    <b>{customer.get('name', '')}</b><br/>
    {customer.get('address', '')}<br/>
    Mobile: {customer.get('mobile', '')}<br/>
    GSTIN: <b>{customer.get('gstin', '') or 'N/A'}</b>
    """
    
    if ship_to and ship_to.get("name"):
        ship_details_html = f"""
        <b>{ship_to.get('name', '')}</b><br/>
        {ship_to.get('address', '')}<br/>
        Mobile: {ship_to.get('mobile', '') or customer.get('mobile', '')}<br/>
        GSTIN: <b>{ship_to.get('gstin', '') or 'N/A'}</b>
        """
        cust_table_data = [
            [Paragraph("<b>BILLED TO (CUSTOMER):</b>", ParagraphStyle('CustHdr', parent=body_bold_style, textColor=primary_color)),
             Paragraph("<b>SHIPPED TO (DELIVERY):</b>", ParagraphStyle('ShipHdr', parent=body_bold_style, textColor=primary_color))],
            [Paragraph(cust_details_html, body_style), Paragraph(ship_details_html, body_style)]
        ]
        cust_table = Table(cust_table_data, colWidths=[255, 255])
        cust_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), secondary_bg),
            ('BOX', (0,0), (0,-1), 0.5, border_color),
            ('BOX', (1,0), (1,-1), 0.5, border_color),
            ('PADDING', (0,0), (-1,-1), 6),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ]))
    else:
        cust_table_data = [
            [Paragraph("<b>BILLED TO (CUSTOMER):</b>", ParagraphStyle('CustHdr', parent=body_bold_style, textColor=primary_color))],
            [Paragraph(cust_details_html, body_style)]
        ]
        cust_table = Table(cust_table_data, colWidths=[520])
        cust_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), secondary_bg),
            ('BOX', (0,0), (-1,-1), 0.5, border_color),
            ('PADDING', (0,0), (-1,-1), 6),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ]))
        
    elements.append(cust_table)
    elements.append(make_spacer(1, 12))

    # 3. Dynamic Items Table (CGST+SGST vs IGST columns)
    invoice_type = invoice_data.get("invoice_type", "Goods")
    gst_treatment = invoice_data.get("gst_treatment", "CGST_SGST")
    items = invoice_data.get("items", [])
    
    is_services = (invoice_type == "Services")
    is_intrastate = (gst_treatment == "CGST_SGST")
    
    # Establish Column Configurations
    if is_services:
        if is_intrastate:
            # Services Intrastate: S.No (20), Description (170), SAC (45), Amount (65), CGST (60), SGST (60), Cess (45), Total (55) = 520
            col_widths = [20, 170, 45, 65, 60, 60, 45, 55]
            items_header = [
                Paragraph("S.N.", table_hdr_style),
                Paragraph("Service Description", ParagraphStyle('HdrL', parent=table_hdr_style, alignment=0)),
                Paragraph("SAC", table_hdr_style),
                Paragraph("Amount", table_hdr_style),
                Paragraph("CGST", table_hdr_style),
                Paragraph("SGST", table_hdr_style),
                Paragraph("Cess", table_hdr_style),
                Paragraph("Total", table_hdr_style)
            ]
        else:
            # Services Interstate: S.No (20), Description (205), SAC (45), Amount (70), IGST (70), Cess (50), Total (60) = 520
            col_widths = [20, 205, 45, 70, 70, 50, 60]
            items_header = [
                Paragraph("S.N.", table_hdr_style),
                Paragraph("Service Description", ParagraphStyle('HdrL', parent=table_hdr_style, alignment=0)),
                Paragraph("SAC", table_hdr_style),
                Paragraph("Amount", table_hdr_style),
                Paragraph("IGST", table_hdr_style),
                Paragraph("Cess", table_hdr_style),
                Paragraph("Total", table_hdr_style)
            ]
    else: # Goods
        if is_intrastate:
            # Goods Intrastate: S.No (20), Product (110), HSN (40), Qty (30), Rate (45), Taxable Value (55), CGST (55), SGST (55), Cess (50), Total (60) = 520
            col_widths = [20, 110, 40, 30, 45, 55, 55, 55, 50, 60]
            items_header = [
                Paragraph("S.N.", table_hdr_style),
                Paragraph("Product Description", ParagraphStyle('HdrL', parent=table_hdr_style, alignment=0)),
                Paragraph("HSN", table_hdr_style),
                Paragraph("Qty", table_hdr_style),
                Paragraph("Rate", table_hdr_style),
                Paragraph("Taxable", table_hdr_style),
                Paragraph("CGST", table_hdr_style),
                Paragraph("SGST", table_hdr_style),
                Paragraph("Cess", table_hdr_style),
                Paragraph("Total", table_hdr_style)
            ]
        else:
            # Goods Interstate: S.No (20), Product (155), HSN (45), Qty (30), Rate (50), Taxable Value (60), IGST (60), Cess (45), Total (55) = 520
            col_widths = [20, 155, 45, 30, 50, 60, 60, 45, 55]
            items_header = [
                Paragraph("S.N.", table_hdr_style),
                Paragraph("Product Description", ParagraphStyle('HdrL', parent=table_hdr_style, alignment=0)),
                Paragraph("HSN", table_hdr_style),
                Paragraph("Qty", table_hdr_style),
                Paragraph("Rate", table_hdr_style),
                Paragraph("Taxable", table_hdr_style),
                Paragraph("IGST", table_hdr_style),
                Paragraph("Cess", table_hdr_style),
                Paragraph("Total", table_hdr_style)
            ]
            
    items_table_data = [items_header]
    
    for idx, item in enumerate(items, 1):
        name = item.get("name", "")
        hsn = item.get("hsn", "") or item.get("hsn_sac", "") or "N/A"
        qty = float(item.get("qty", 0))
        rate = float(item.get("rate", 0))
        taxable = float(item.get("taxable_amount", qty * rate))
        gst_rate = float(item.get("gst_rate", 0))
        cgst_amt = float(item.get("cgst_amount", 0))
        sgst_amt = float(item.get("sgst_amount", 0))
        igst_amt = float(item.get("igst_amount", 0))
        cess_rate = float(item.get("cess_rate", 0))
        cess_amt = float(item.get("cess_amount", 0))
        total = float(item.get("total_amount", taxable))
        
        # Build cell layouts
        cell_sn = Paragraph(str(idx), table_cell_center_style)
        cell_name = Paragraph(name, table_cell_style)
        cell_hsn = Paragraph(hsn, table_cell_center_style)
        cell_taxable = Paragraph(f"{taxable:,.2f}", table_cell_right_style)
        
        cell_cgst = Paragraph(f"{gst_rate/2:g}%<br/>{cgst_amt:,.2f}", table_cell_right_style)
        cell_sgst = Paragraph(f"{gst_rate/2:g}%<br/>{sgst_amt:,.2f}", table_cell_right_style)
        cell_igst = Paragraph(f"{gst_rate:g}%<br/>{igst_amt:,.2f}", table_cell_right_style)
        cell_cess = Paragraph(f"{cess_rate:g}%<br/>{cess_amt:,.2f}", table_cell_right_style)
        cell_total = Paragraph(f"{total:,.2f}", table_cell_right_style)
        
        if is_services:
            if is_intrastate:
                row = [cell_sn, cell_name, cell_hsn, cell_taxable, cell_cgst, cell_sgst, cell_cess, cell_total]
            else:
                row = [cell_sn, cell_name, cell_hsn, cell_taxable, cell_igst, cell_cess, cell_total]
        else:
            cell_qty = Paragraph(f"{qty:g}", table_cell_center_style)
            cell_rate = Paragraph(f"{rate:,.2f}", table_cell_right_style)
            if is_intrastate:
                row = [cell_sn, cell_name, cell_hsn, cell_qty, cell_rate, cell_taxable, cell_cgst, cell_sgst, cell_cess, cell_total]
            else:
                row = [cell_sn, cell_name, cell_hsn, cell_qty, cell_rate, cell_taxable, cell_igst, cell_cess, cell_total]
                
        items_table_data.append(row)
        
    items_table = Table(items_table_data, colWidths=col_widths, repeatRows=1)
    
    # Establish grid style
    t_style = list(table_grid_style)
    
    for r in range(1, len(items_table_data)):
        if r % 2 == 0:
            t_style.append(('BACKGROUND', (0, r), (-1, r), colors.HexColor("#F8FAFC")))
            
    items_table.setStyle(TableStyle(t_style))
    elements.append(items_table)
    elements.append(make_spacer(1, 10))

    # 4. Calculation Summary and GST Breakout Footer
    summary = invoice_data.get("summary", {})
    subtotal = summary.get("subtotal", 0.0)
    cgst_total = summary.get("cgst_total", 0.0)
    sgst_total = summary.get("sgst_total", 0.0)
    igst_total = summary.get("igst_total", 0.0)
    cess_total = summary.get("cess_total", 0.0)
    round_off = summary.get("round_off", 0.0)
    grand_total = summary.get("grand_total", 0.0)
    
    is_rcm = invoice_data.get("rcm", False)
    total_words = num_to_words_indian(grand_total)
    
    # Display message if Reverse Charge is enabled
    rcm_msg_html = ""
    if is_rcm:
        rcm_tax_total = cgst_total + sgst_total + igst_total
        rcm_msg_html = f"""
        <br/><br/>
        <font color="#B91C1C"><b>* TAX PAYABLE UNDER REVERSE CHARGE (RCM): ₹ {rcm_tax_total:,.2f}</b><br/>
        (The tax is payable directly by the recipient to the government and is excluded from this invoice grand total.)</font>
        """
        
    left_summary_html = f"""
    <b>Amount in Words:</b><br/>
    <i>{total_words}</i>
    {rcm_msg_html}
    """
    
    # Build calculations breakdown
    right_summary_data = [
        [Paragraph("Taxable Value:", body_style), Paragraph(f"{subtotal:,.2f}", table_cell_right_style)],
    ]
    
    if is_intrastate:
        right_summary_data.append([Paragraph("CGST Amount:", body_style), Paragraph(f"{cgst_total:,.2f}", table_cell_right_style)])
        right_summary_data.append([Paragraph("SGST Amount:", body_style), Paragraph(f"{sgst_total:,.2f}", table_cell_right_style)])
    else:
        right_summary_data.append([Paragraph("IGST Amount:", body_style), Paragraph(f"{igst_total:,.2f}", table_cell_right_style)])
        
    if cess_total > 0:
        right_summary_data.append([Paragraph("GST Cess:", body_style), Paragraph(f"{cess_total:,.2f}", table_cell_right_style)])
        
    right_summary_data.extend([
        [Paragraph("Round Off:", body_style), Paragraph(f"{round_off:+.2f}", table_cell_right_style)],
        [Paragraph("<b>Grand Total:</b>", ParagraphStyle('GrandLbl', parent=body_style, fontName='Helvetica-Bold', fontSize=10, textColor=primary_color)), 
         Paragraph(f"<b>₹ {grand_total:,.2f}</b>", ParagraphStyle('GrandVal', parent=table_cell_bold_right_style, fontSize=10, textColor=primary_color))]
    ])
    
    right_summary_table = Table(right_summary_data, colWidths=[120, 90])
    right_summary_table.setStyle(TableStyle([
        ('LINEBELOW', (0,0), (-1,-2), 0.5, border_color),
        ('LINEABOVE', (0,-1), (-1,-1), 1, primary_color),
        ('LINEBELOW', (0,-1), (-1,-1), 1.5, primary_color),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
    ]))
    
    summary_outer_data = [
        [Paragraph(left_summary_html, body_style), right_summary_table]
    ]
    summary_outer_table = Table(summary_outer_data, colWidths=[310, 210])
    summary_outer_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
    ]))
    
    elements.append(summary_outer_table)
    elements.append(make_spacer(1, 12))

    # 5. Footer: Bank Details & Declaration & Signatory
    bank_name = seller.get("bank_name", "")
    acc_no = seller.get("account_number", "")
    ifsc = seller.get("ifsc", "")
    branch = seller.get("branch", "")
    declaration = seller.get("declaration", "")
    
    bank_details_html = f"""
    <b>Bank Details for Payment:</b><br/>
    Bank Name: {bank_name}<br/>
    Account No: {acc_no}<br/>
    IFSC Code: {ifsc}<br/>
    Branch: {branch}
    """
    
    decl_html = f"""
    <b>Declaration:</b><br/>
    {declaration}
    """
    
    signatory_html = f"""
    <br/><br/><br/>
    For <b>{seller.get('trade_name', '')}</b>
    <br/><br/>
    Authorized Signatory
    """
    
    footer_cols_data = [
        [
            [Paragraph(bank_details_html, body_style), make_spacer(1, 8), Paragraph(decl_html, ParagraphStyle('DeclStyle', parent=body_style, fontSize=7, leading=9, textColor=colors.HexColor("#718096")))],
            Paragraph(signatory_html, ParagraphStyle('SignStyle', parent=body_style, alignment=1))
        ]
    ]
    
    footer_cols_table = Table(footer_cols_data, colWidths=[340, 180])
    footer_cols_table.setStyle(TableStyle([
        ('BOX', (0,0), (0,0), 0.5, border_color),
        ('BOX', (1,0), (1,0), 0.5, border_color),
        ('BACKGROUND', (0,0), (-1,-1), secondary_bg),
        ('PADDING', (0,0), (-1,-1), 6),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
    ]))
    
    elements.append(KeepTogether(footer_cols_table))

    doc.build(elements, canvasmaker=NumberedCanvas)
