import { Inbox, ShieldCheck } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { AGEING_ALERT, AGEING_WARN, PRIORITY_VAR, stageVar } from '@/lib/constants'
import { cn } from '@/lib/utils'
import type { TaskPriority } from '@/types/db'

export function PageHeader({
  title,
  description,
  children,
}: {
  title: string
  description?: string
  children?: React.ReactNode
}) {
  return (
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div className="min-w-0">
        <h1 className="text-foreground truncate text-2xl font-semibold tracking-tight">{title}</h1>
        {description ? (
          <p className="text-muted-foreground mt-0.5 text-sm">{description}</p>
        ) : null}
      </div>
      {children ? <div className="flex shrink-0 items-center gap-2">{children}</div> : null}
    </div>
  )
}

export function StatCard({
  label,
  value,
  icon: Icon,
  tone = 'default',
  hint,
}: {
  label: string
  value: React.ReactNode
  icon?: React.ComponentType<{ className?: string }>
  tone?: 'default' | 'destructive' | 'success' | 'accent'
  hint?: string
}) {
  const toneClass = {
    default: 'text-foreground',
    destructive: 'text-destructive',
    success: 'text-success',
    accent: 'text-accent',
  }[tone]

  return (
    <Card className="gap-0 py-4">
      <CardContent className="flex items-start justify-between gap-3 px-4">
        <div className="min-w-0">
          <p className="text-muted-foreground text-xs font-medium tracking-wide uppercase">
            {label}
          </p>
          <p className={cn('mt-1 text-2xl font-semibold tabular-nums', toneClass)}>{value}</p>
          {hint ? <p className="text-muted-foreground mt-0.5 text-xs">{hint}</p> : null}
        </div>
        {Icon ? (
          <div
            className={cn('bg-muted grid size-9 shrink-0 place-items-center rounded-md', toneClass)}
          >
            <Icon className="size-4" />
          </div>
        ) : null}
      </CardContent>
    </Card>
  )
}

export function StageBadge({
  code,
  name,
  showCode = false,
}: {
  code: string
  name: string
  showCode?: boolean
}) {
  const colour = stageVar(code)
  return (
    <span
      className="inline-flex items-center gap-1.5 rounded-md border px-2 py-0.5 text-xs font-medium whitespace-nowrap"
      style={{
        color: colour,
        borderColor: colour,
        backgroundColor: `color-mix(in srgb, ${colour} 10%, transparent)`,
      }}
    >
      <span className="size-1.5 rounded-full" style={{ backgroundColor: colour }} />
      {showCode ? <span className="opacity-70 tabular-nums">{code}</span> : null}
      {name}
    </span>
  )
}

/**
 * How long a task has sat in its current stage. This replaced the old
 * efficiency metrics: it measures the work getting stuck, not the person.
 */
export function AgeingBadge({
  days,
  terminal = false,
}: {
  days: number
  terminal?: boolean
}) {
  if (terminal) {
    return <span className="text-muted-foreground text-xs whitespace-nowrap">—</span>
  }

  const tone =
    days >= AGEING_ALERT
      ? 'text-destructive font-semibold'
      : days >= AGEING_WARN
        ? 'text-warning font-medium'
        : 'text-muted-foreground'

  return (
    <span className={cn('text-xs whitespace-nowrap tabular-nums', tone)}>
      {days === 0 ? 'today' : days === 1 ? '1 day' : `${days} days`}
    </span>
  )
}

export function PriorityBadge({ priority }: { priority: TaskPriority }) {
  return (
    <span
      className="inline-flex items-center rounded-md px-2 py-0.5 text-xs font-medium whitespace-nowrap"
      style={{
        color: PRIORITY_VAR[priority],
        backgroundColor: `color-mix(in srgb, ${PRIORITY_VAR[priority]} 12%, transparent)`,
      }}
    >
      {priority}
    </span>
  )
}

export function CategoryBadge({ category }: { category: string }) {
  return (
    <Badge variant="secondary" className="font-normal whitespace-nowrap">
      {category}
    </Badge>
  )
}

/** Marks a task generated by the compliance engine. */
export function ComplianceBadge({ gstin }: { gstin?: string | null }) {
  return (
    <Badge variant="outline" className="border-primary/40 gap-1 font-normal whitespace-nowrap">
      <ShieldCheck className="size-3" />
      Compliance
      {gstin ? <span className="font-mono text-[10px]">{gstin.slice(0, 2)}</span> : null}
    </Badge>
  )
}

/**
 * Not yet due: "due in Xd". Shown only inside a 45-day window so far-off
 * annual items do not shout from every list.
 */
export function UpcomingBadge({ days }: { days?: number | null }) {
  if (typeof days !== 'number' || days < 0 || days > 45) return null
  return (
    <span
      className="inline-flex items-center rounded-md border px-2 py-0.5 text-xs font-medium whitespace-nowrap"
      style={{
        color: 'var(--stage-02)',
        borderColor: 'var(--stage-02)',
        backgroundColor: 'color-mix(in srgb, var(--stage-02) 8%, transparent)',
      }}
    >
      {days === 0 ? 'due today' : days === 1 ? 'due tomorrow' : `due in ${days}d`}
    </span>
  )
}

export function OverdueBadge({ days }: { days?: number | null }) {
  return (
    <Badge variant="destructive" className="whitespace-nowrap">
      {typeof days === 'number' && days < 0 ? `${Math.abs(days)}d overdue` : 'Overdue'}
    </Badge>
  )
}

export function EmptyState({
  title,
  description,
  action,
  icon: Icon = Inbox,
}: {
  title: string
  description?: string
  action?: React.ReactNode
  icon?: React.ComponentType<{ className?: string }>
}) {
  return (
    <div className="flex flex-col items-center justify-center gap-3 rounded-lg border border-dashed px-6 py-14 text-center">
      <div className="bg-muted text-muted-foreground grid size-11 place-items-center rounded-full">
        <Icon className="size-5" />
      </div>
      <div>
        <p className="font-medium">{title}</p>
        {description ? (
          <p className="text-muted-foreground mt-1 max-w-md text-sm">{description}</p>
        ) : null}
      </div>
      {action}
    </div>
  )
}

export function TableSkeleton({ rows = 6, cols = 5 }: { rows?: number; cols?: number }) {
  return (
    <div className="space-y-2 p-4">
      {Array.from({ length: rows }).map((_, r) => (
        <div key={r} className="flex gap-3">
          {Array.from({ length: cols }).map((__, c) => (
            <Skeleton key={c} className={cn('h-8 flex-1', c === 0 && 'flex-[2]')} />
          ))}
        </div>
      ))}
    </div>
  )
}

export function Field({
  label,
  htmlFor,
  error,
  hint,
  required,
  className,
  children,
}: {
  label: string
  htmlFor?: string
  error?: string | null
  hint?: string
  required?: boolean
  className?: string
  children: React.ReactNode
}) {
  return (
    <div className={cn('space-y-1.5', className)}>
      <label htmlFor={htmlFor} className="text-foreground text-sm font-medium">
        {label}
        {required ? <span className="text-destructive ml-0.5">*</span> : null}
      </label>
      {children}
      {error ? <p className="text-destructive text-xs">{error}</p> : null}
      {!error && hint ? <p className="text-muted-foreground text-xs">{hint}</p> : null}
    </div>
  )
}
