-- =====================================================================
--  FILE 11 : Compliance rule catalogue, generated from
--  seed_compliance_master.xlsx (71 rules). Run AFTER 10.
--
--  is_generatable = true  -> the morning job creates dated tasks from it
--  is_generatable = false -> event-driven; created manually from Task Master
--
--  Safe to re-run: existing codes are updated, not duplicated.
-- =====================================================================

insert into public.compliance_master (
  code, name, law, entity_types, target_level, alt_group, frequency,
  frequency_overridable, period_basis, due_rule_type, due_anchor, due_day,
  due_month, due_event, due_offset_days, period_due_dates, due_rule_text,
  is_generatable, default_applicable, active, notes
) values
  ('IT_ITR_NONAUDIT', 'ITR (non audit)', 'Income Tax', 'All', 'Client', 'ITR', 'Annual', false, 'Assessment Year', 'fixed_annual', 'next_after_period', 31, 7, null, null, null, '31 Jul after FY', true, true, true, 'Pick one ITR variant per client (alt_group ITR)'),
  ('IT_ITR_AUDIT', 'ITR (audit case)', 'Income Tax', 'All', 'Client', 'ITR', 'Annual', false, 'Assessment Year', 'fixed_annual', 'next_after_period', 31, 10, null, null, null, '31 Oct after FY', true, false, true, 'Mutually exclusive with other ITR rows'),
  ('IT_ITR_TP', 'ITR (TP case, 3CEB applicable)', 'Income Tax', 'All', 'Client', 'ITR', 'Annual', false, 'Assessment Year', 'fixed_annual', 'next_after_period', 30, 11, null, null, null, '30 Nov after FY', true, false, true, 'Mutually exclusive with other ITR rows'),
  ('IT_TAR', 'Tax Audit Report (3CA-3CD or 3CB-3CD)', 'Income Tax', 'All', 'Client', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'next_after_period', 30, 9, null, null, null, '30 Sep after FY', true, false, true, 'Turn on only where tax audit applies'),
  ('IT_3CEB', 'Form 3CEB (Transfer Pricing)', 'Income Tax', 'All', 'Client', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'next_after_period', 31, 10, null, null, null, '31 Oct after FY', true, false, true, 'Turn on for international or specified domestic TP'),
  ('IT_TDS_PAY', 'TDS payment (challan)', 'Income Tax', 'All', 'Client', null, 'Monthly', false, 'Calendar Period', 'period_relative', 'next_month', 7, null, null, null, null, '7th of next month', true, true, true, 'March deduction payable by 30 Apr'),
  ('IT_TCS_PAY', 'TCS payment (challan)', 'Income Tax', 'All', 'Client', null, 'Monthly', false, 'Calendar Period', 'period_relative', 'next_month', 7, null, null, null, null, '7th of next month', true, false, true, null),
  ('IT_24Q', 'TDS Return 24Q (salary)', 'Income Tax', 'All', 'Client', null, 'Quarterly', false, 'Calendar Period', 'quarterly_schedule', null, null, null, null, null, 'Q1=31-Jul; Q2=31-Oct; Q3=31-Jan; Q4=31-May', 'Quarterly, Q4 due 31 May', true, false, true, 'Year resolved as first occurrence after each quarter end'),
  ('IT_26Q', 'TDS Return 26Q (non salary)', 'Income Tax', 'All', 'Client', null, 'Quarterly', false, 'Calendar Period', 'quarterly_schedule', null, null, null, null, null, 'Q1=31-Jul; Q2=31-Oct; Q3=31-Jan; Q4=31-May', 'Quarterly, Q4 due 31 May', true, true, true, null),
  ('IT_27Q', 'TDS Return 27Q (non resident)', 'Income Tax', 'All', 'Client', null, 'Quarterly', false, 'Calendar Period', 'quarterly_schedule', null, null, null, null, null, 'Q1=31-Jul; Q2=31-Oct; Q3=31-Jan; Q4=31-May', 'Quarterly, Q4 due 31 May', true, false, true, null),
  ('IT_27EQ', 'TCS Return 27EQ', 'Income Tax', 'All', 'Client', null, 'Quarterly', false, 'Calendar Period', 'quarterly_schedule', null, null, null, null, null, 'Q1=15-Jul; Q2=15-Oct; Q3=15-Jan; Q4=15-May', 'Quarterly TCS return', true, false, true, null),
  ('IT_FORM16', 'Form 16 (salary certificate)', 'Income Tax', 'All', 'Client', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'next_after_period', 15, 6, null, null, null, '15 Jun after FY', true, false, true, 'Issued to employees'),
  ('IT_FORM16A', 'Form 16A (TDS certificate)', 'Income Tax', 'All', 'Client', null, 'Quarterly', false, 'Calendar Period', 'quarterly_schedule', null, null, null, null, null, 'Q1=15-Aug; Q2=15-Nov; Q3=15-Feb; Q4=15-Jun', 'Within 15 days of TDS return due date', true, false, true, null),
  ('IT_FORM27D', 'Form 27D (TCS certificate)', 'Income Tax', 'All', 'Client', null, 'Quarterly', false, 'Calendar Period', 'quarterly_schedule', null, null, null, null, null, 'Q1=30-Jul; Q2=30-Oct; Q3=30-Jan; Q4=30-May', 'Within 15 days of 27EQ due date', true, false, true, null),
  ('IT_ADV_TAX', 'Advance Tax', 'Income Tax', 'All', 'Client', null, 'Quarterly', false, 'Financial Year', 'quarterly_schedule', null, null, null, null, null, 'Q1=15-Jun; Q2=15-Sep; Q3=15-Dec; Q4=15-Mar', 'Instalments 15/45/75/100 percent', true, true, true, null),
  ('IT_SFT', 'SFT (Form 61A)', 'Income Tax', 'All', 'Client', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'next_after_period', 31, 5, null, null, null, '31 May after FY', true, false, true, 'Only reporting persons'),
  ('IT_15CACB', 'Form 15CA / 15CB (foreign remittance)', 'Income Tax', 'All', 'Client', null, 'Event', false, 'Event', 'event', null, null, null, 'EVT', null, null, 'Per remittance, before payment', false, false, true, 'Create via Adhoc module'),
  ('IT_15GH', 'Form 15G / 15H (quarterly upload)', 'Income Tax', 'All', 'Client', null, 'Quarterly', false, 'Calendar Period', 'quarterly_schedule', null, null, null, null, null, 'Q1=15-Jul; Q2=15-Oct; Q3=15-Jan; Q4=30-Apr', 'Confirm Q4 date for the year', true, false, true, null),
  ('IT_EQ_LEVY', 'Equalisation Levy (Form 1)', 'Income Tax', 'All', 'Client', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'next_after_period', 30, 6, null, null, null, '30 Jun after FY', true, false, true, null),
  ('IT_PANTAN', 'PAN / TAN application or correction', 'Income Tax', 'All', 'Client', null, 'Event', false, 'Event', 'event', null, null, null, 'EVT', null, null, 'On requirement', false, false, true, 'Create via Adhoc module'),
  ('GST_GSTR1_M', 'GSTR-1 (monthly)', 'GST', 'All', 'GSTIN', 'GSTR1', 'Monthly', true, 'Calendar Period', 'period_relative', 'next_month', 11, null, null, null, null, '11th of next month', true, true, true, 'Generator uses GSTIN frequency to pick monthly vs QRMP'),
  ('GST_GSTR1_Q', 'GSTR-1 (QRMP quarterly)', 'GST', 'All', 'GSTIN', 'GSTR1', 'Quarterly', true, 'Calendar Period', 'period_relative', 'next_month', 13, null, null, null, null, '13th of month after quarter', true, false, true, 'Used when GSTIN frequency is QRMP'),
  ('GST_IFF', 'IFF (QRMP optional)', 'GST', 'All', 'GSTIN', null, 'Monthly', false, 'Calendar Period', 'period_relative', 'next_month', 13, null, null, null, null, '13th of next month (M1, M2 only)', true, false, true, 'Optional for QRMP taxpayers'),
  ('GST_GSTR3B_M', 'GSTR-3B (monthly)', 'GST', 'All', 'GSTIN', 'GSTR3B', 'Monthly', true, 'Calendar Period', 'period_relative', 'next_month', 20, null, null, null, null, '20th of next month', true, true, true, 'Generator uses GSTIN frequency to pick monthly vs QRMP'),
  ('GST_GSTR3B_Q', 'GSTR-3B (QRMP quarterly)', 'GST', 'All', 'GSTIN', 'GSTR3B', 'Quarterly', true, 'Calendar Period', 'period_relative', 'next_month', 22, null, null, null, null, '22nd or 24th by state group', true, false, true, 'Confirm 22 vs 24 by state group'),
  ('GST_PMT06', 'PMT-06 (QRMP monthly tax)', 'GST', 'All', 'GSTIN', null, 'Monthly', false, 'Calendar Period', 'period_relative', 'next_month', 25, null, null, null, null, '25th of next month (M1, M2)', true, false, true, 'QRMP monthly tax payment'),
  ('GST_CMP08', 'CMP-08 (composition)', 'GST', 'All', 'GSTIN', null, 'Quarterly', false, 'Calendar Period', 'period_relative', 'next_month', 18, null, null, null, null, '18th of month after quarter', true, false, true, 'Composition dealers only'),
  ('GST_GSTR4', 'GSTR-4 (composition annual)', 'GST', 'All', 'GSTIN', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'next_after_period', 30, 6, null, null, null, '30 Jun after FY', true, false, true, 'Composition dealers only'),
  ('GST_GSTR9', 'GSTR-9 (annual return)', 'GST', 'All', 'GSTIN', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'next_after_period', 31, 12, null, null, null, '31 Dec after FY', true, false, true, 'Threshold based applicability, staff decides'),
  ('GST_GSTR9C', 'GSTR-9C (reconciliation)', 'GST', 'All', 'GSTIN', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'next_after_period', 31, 12, null, null, null, '31 Dec after FY', true, false, true, 'Threshold based applicability, staff decides'),
  ('GST_GSTR6', 'GSTR-6 (Input Service Distributor)', 'GST', 'All', 'GSTIN', null, 'Monthly', false, 'Calendar Period', 'period_relative', 'next_month', 13, null, null, null, null, '13th of next month', true, false, true, 'ISD registrations only'),
  ('GST_GSTR7', 'GSTR-7 (TDS under GST)', 'GST', 'All', 'GSTIN', null, 'Monthly', false, 'Calendar Period', 'period_relative', 'next_month', 10, null, null, null, null, '10th of next month', true, false, true, 'GST TDS deductors only'),
  ('GST_GSTR8', 'GSTR-8 (TCS, e-commerce)', 'GST', 'All', 'GSTIN', null, 'Monthly', false, 'Calendar Period', 'period_relative', 'next_month', 10, null, null, null, null, '10th of next month', true, false, true, 'E-commerce operators only'),
  ('GST_GSTR5', 'GSTR-5 / 5A (non resident / OIDAR)', 'GST', 'All', 'GSTIN', null, 'Monthly', false, 'Calendar Period', 'period_relative', 'next_month', 13, null, null, null, null, '5 = 13th, 5A = 20th of next month', true, false, true, 'Split into two rows if both apply'),
  ('GST_ITC04', 'ITC-04 (job work)', 'GST', 'All', 'GSTIN', null, 'Half Yearly', false, 'Financial Year', 'half_yearly_schedule', null, null, null, null, null, 'H1=25-Oct; H2=25-Apr', 'Half yearly or annual by turnover', true, false, true, 'Confirm frequency by turnover'),
  ('GST_LUT', 'LUT (zero rated bond exemption)', 'GST', 'All', 'GSTIN', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'before_period', 31, 3, null, null, null, 'Before FY start, by 31 Mar', true, false, true, 'Exporters and zero rated supplies'),
  ('GST_GSTR10', 'GSTR-10 (final return)', 'GST', 'All', 'GSTIN', null, 'Event', false, 'Event', 'event', null, null, null, 'EVT', 90, null, 'Within 3 months of cancellation', false, false, true, 'Create via Adhoc module'),
  ('GST_ITC_RECON', 'ITC Reconciliation (internal)', 'GST', 'All', 'GSTIN', null, 'Monthly', false, 'Calendar Period', 'internal', null, null, null, null, null, null, 'Firm defined', false, false, true, 'Internal working, not a portal filing'),
  ('GST_2B_RECON', 'GSTR-2B Reconciliation (internal)', 'GST', 'All', 'GSTIN', null, 'Monthly', false, 'Calendar Period', 'internal', null, null, null, null, null, null, 'Firm defined', false, false, true, 'Internal working, not a portal filing'),
  ('GST_RCM', 'RCM Working (internal)', 'GST', 'All', 'GSTIN', null, 'Monthly', false, 'Calendar Period', 'internal', null, null, null, null, null, null, 'Firm defined', false, false, true, 'Internal working, not a portal filing'),
  ('MCA_AGM', 'AGM (event the forms anchor to)', 'MCA-ROC', 'Company', 'Client', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'next_after_period', 30, 9, null, null, null, 'By 30 Sep after FY', true, true, true, 'Capture actual AGM date; AOC-4 and MGT-7 anchor to it'),
  ('MCA_AOC4', 'AOC-4 (financial statements)', 'MCA-ROC', 'Company', 'Client', null, 'Annual', false, 'Financial Year', 'event_anchored', 'event', null, null, 'AGM', 30, null, 'AGM + 30 days', true, true, true, 'Provisional AGM 30 Sep until actual entered'),
  ('MCA_AOC4_XBRL', 'AOC-4 XBRL / CFS / NBFC variant', 'MCA-ROC', 'Company', 'Client', null, 'Annual', false, 'Financial Year', 'event_anchored', 'event', null, null, 'AGM', 30, null, 'AGM + 30 days', true, false, true, 'Turn on where XBRL or CFS applies'),
  ('MCA_CSR2', 'CSR-2 (CSR report, linked to AOC-4)', 'MCA-ROC', 'Company', 'Client', null, 'Annual', false, 'Financial Year', 'event_anchored', 'event', null, null, 'AGM', 30, null, 'With or after AOC-4, as notified', true, false, true, 'Only where CSR applies'),
  ('MCA_MGT7', 'MGT-7 (annual return)', 'MCA-ROC', 'Company', 'Client', 'MGT7', 'Annual', false, 'Financial Year', 'event_anchored', 'event', null, null, 'AGM', 60, null, 'AGM + 60 days', true, true, true, 'Mutually exclusive with MGT-7A'),
  ('MCA_MGT7A', 'MGT-7A (annual return, small co / OPC)', 'MCA-ROC', 'Company', 'Client', 'MGT7', 'Annual', false, 'Financial Year', 'event_anchored', 'event', null, null, 'AGM', 60, null, 'AGM + 60 days', true, false, true, 'Small company or OPC variant'),
  ('MCA_ADT1', 'ADT-1 (auditor appointment)', 'MCA-ROC', 'Company', 'Client', null, 'Annual', false, 'Financial Year', 'event_anchored', 'event', null, null, 'AGM', 15, null, 'AGM + 15 days, or INC + 30 on first appointment', true, false, true, 'Filed in year of appointment'),
  ('MCA_DIR3KYC_CO', 'DIR-3 KYC (directors)', 'MCA-ROC', 'Company', 'Client', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'next_after_period', 30, 9, null, null, null, '30 Sep, configurable', true, true, true, 'Timing in flux, override per FY | Person-level in the old tracker: tick this on the individual''s own client row.'),
  ('MCA_DPT3', 'DPT-3 (return of deposits)', 'MCA-ROC', 'Company', 'Client', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'next_after_period', 30, 6, null, null, null, '30 Jun after FY', true, true, true, null),
  ('MCA_MSME1', 'MSME-1 (dues to MSME vendors)', 'MCA-ROC', 'Company', 'Client', null, 'Half Yearly', false, 'Calendar Period', 'half_yearly_schedule', null, null, null, null, null, 'H1=31-Oct; H2=30-Apr', 'Apr-Sep due 31 Oct; Oct-Mar due 30 Apr', true, false, true, 'Only if outstanding to MSME suppliers'),
  ('MCA_PAS6', 'PAS-6 (share capital reconciliation)', 'MCA-ROC', 'Company', 'Client', null, 'Half Yearly', false, 'Calendar Period', 'half_yearly_schedule', null, null, null, null, null, 'H1=29-Nov; H2=30-May', 'Within 60 days of each half year end', true, false, true, 'Unlisted public and prescribed companies'),
  ('MCA_INC20A', 'INC-20A (commencement of business)', 'MCA-ROC', 'Company', 'Client', null, 'One Time', false, 'Event', 'one_time', 'event', null, null, 'INC', 180, null, 'Incorporation + 180 days', false, false, true, 'Companies incorporated after Nov 2019'),
  ('MCA_INC22A', 'INC-22A / ACTIVE (office tagging)', 'MCA-ROC', 'Company', 'Client', null, 'Event', false, 'Event', 'event', null, null, null, 'EVT', null, null, 'As required', false, false, true, null),
  ('MCA_BEN2', 'BEN-2 (significant beneficial owner)', 'MCA-ROC', 'Company', 'Client', null, 'Event', false, 'Event', 'event', null, null, null, 'EVT', 30, null, 'Within 30 days of trigger', false, false, true, 'Create via Adhoc module'),
  ('MCA_MGT14', 'MGT-14 (board / special resolutions)', 'MCA-ROC', 'Company', 'Client', null, 'Event', false, 'Event', 'event', null, null, null, 'EVT', 30, null, 'Within 30 days of resolution', false, false, true, 'Create via Adhoc module'),
  ('MCA_DIR12', 'DIR-12 (director change)', 'MCA-ROC', 'Company', 'Client', null, 'Event', false, 'Event', 'event', null, null, null, 'EVT', 30, null, 'Within 30 days of change', false, false, true, 'Create via Adhoc module'),
  ('MCA_PAS3', 'PAS-3 (allotment of shares)', 'MCA-ROC', 'Company', 'Client', null, 'Event', false, 'Event', 'event', null, null, null, 'EVT', 30, null, 'Within 30 days of allotment', false, false, true, 'Create via Adhoc module'),
  ('MCA_CHG1', 'CHG-1 / CHG-4 (charge create / satisfy)', 'MCA-ROC', 'Company', 'Client', null, 'Event', false, 'Event', 'event', null, null, null, 'EVT', 30, null, 'Within 30 days of event', false, false, true, 'Create via Adhoc module'),
  ('MCA_BOARD', 'Board Meetings (count tracker)', 'MCA-ROC', 'Company', 'Client', null, 'Quarterly', false, 'Financial Year', 'internal', null, null, null, null, null, null, '4 per year, 2 for small company', false, false, true, 'Optional governance tracker'),
  ('LLP_FORM11', 'Form 11 (annual return)', 'MCA-ROC', 'LLP', 'Client', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'next_after_period', 30, 5, null, null, null, '30 May after FY', true, true, true, null),
  ('LLP_FORM8', 'Form 8 (Statement of Account and Solvency)', 'MCA-ROC', 'LLP', 'Client', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'next_after_period', 30, 10, null, null, null, '30 Oct after FY', true, true, true, null),
  ('LLP_DIR3KYC', 'DIR-3 KYC (designated partners)', 'MCA-ROC', 'LLP', 'Client', null, 'Annual', false, 'Financial Year', 'fixed_annual', 'next_after_period', 30, 9, null, null, null, '30 Sep, configurable', true, true, true, 'Timing in flux, override per FY | Person-level in the old tracker: tick this on the individual''s own client row.'),
  ('LLP_FORM3', 'Form 3 (LLP agreement change)', 'MCA-ROC', 'LLP', 'Client', null, 'Event', false, 'Event', 'event', null, null, null, 'EVT', 30, null, 'Within 30 days of change', false, false, true, 'Create via Adhoc module'),
  ('LLP_FORM4', 'Form 4 (partner change)', 'MCA-ROC', 'LLP', 'Client', null, 'Event', false, 'Event', 'event', null, null, null, 'EVT', 30, null, 'Within 30 days of change', false, false, true, 'Create via Adhoc module'),
  ('LLP_FORM5', 'Form 5 (name change)', 'MCA-ROC', 'LLP', 'Client', null, 'Event', false, 'Event', 'event', null, null, null, 'EVT', null, null, 'On ROC approval', false, false, true, 'Create via Adhoc module'),
  ('LLP_FORM15', 'Form 15 (registered office change)', 'MCA-ROC', 'LLP', 'Client', null, 'Event', false, 'Event', 'event', null, null, null, 'EVT', 30, null, 'Within 30 days of change', false, false, true, 'Create via Adhoc module'),
  ('LAB_PF', 'PF (ECR)', 'Labour', 'All', 'Client', null, 'Monthly', false, 'Calendar Period', 'period_relative', 'next_month', 15, null, null, null, null, '15th of next month', true, false, true, 'Turn on for registered establishments'),
  ('LAB_ESI', 'ESI contribution', 'Labour', 'All', 'Client', null, 'Monthly', false, 'Calendar Period', 'period_relative', 'next_month', 15, null, null, null, null, '15th of next month', true, false, true, 'Turn on for registered establishments'),
  ('LAB_PT', 'Professional Tax (PT)', 'Labour', 'All', 'Client', null, 'Monthly', false, 'Calendar Period', 'periodic', null, null, null, null, null, null, 'Per state, monthly or annual', false, false, true, 'State specific, confirm frequency and date'),
  ('LAB_LWF', 'Labour Welfare Fund (LWF)', 'Labour', 'All', 'Client', null, 'Half Yearly', false, 'Calendar Period', 'periodic', null, null, null, null, null, null, 'Per state, half yearly or annual', false, false, true, 'State specific, confirm frequency and date'),
  ('LAB_SHOPS', 'Shops and Establishment (renewal)', 'Labour', 'All', 'Client', null, 'Periodic', false, 'Event', 'periodic', null, null, null, null, null, null, 'Per state registration validity', false, false, true, 'State specific renewal cycle')
on conflict (code) do update set
  name = excluded.name,
  law = excluded.law,
  entity_types = excluded.entity_types,
  target_level = excluded.target_level,
  alt_group = excluded.alt_group,
  frequency = excluded.frequency,
  frequency_overridable = excluded.frequency_overridable,
  period_basis = excluded.period_basis,
  due_rule_type = excluded.due_rule_type,
  due_anchor = excluded.due_anchor,
  due_day = excluded.due_day,
  due_month = excluded.due_month,
  due_event = excluded.due_event,
  due_offset_days = excluded.due_offset_days,
  period_due_dates = excluded.period_due_dates,
  due_rule_text = excluded.due_rule_text,
  is_generatable = excluded.is_generatable,
  active = excluded.active,
  notes = excluded.notes;

-- Verify:
--   select count(*) filter (where is_generatable) as generatable,
--          count(*) filter (where target_level = 'GSTIN') as per_gstin,
--          count(*) as total
--   from public.compliance_master;
