from flask import Flask, request, jsonify, send_file, render_template, send_from_directory
import os
import sys
import threading
import webbrowser
import unittest
import json
import sqlite3
import io

# Import internal modules
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.db import init_db, get_connection, backup_db, restore_db, log_audit
from src.import_engine import parse_tally_excel, parse_tally_csv, parse_tally_xml, save_imported_ledgers, load_sample_trial_balance, generate_sample_excel_file
from src.mapping_engine import execute_auto_mapping, update_single_mapping, bulk_map_tally_group, get_mapping_register
from src.reconciliation_engine import run_reconciliation_check
from src.statement_generator import generate_financial_statements, get_company_profile, generate_notes
from src.export_engine import export_excel_working_papers, export_word_draft, export_pdf_report
from src.tally_converter import convert_tally_excel, convert_tally_csv, generate_app_format_excel


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(BASE_DIR)
STATIC_DIR = os.path.join(BASE_DIR, "static")
TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")

app = Flask(__name__, static_folder=STATIC_DIR, static_url_path='')

# Initialize DB schema on startup
init_db()

@app.route('/')
def index():
    return send_from_directory(STATIC_DIR, 'index.html')

@app.route('/styles.css')
def serve_css():
    return send_from_directory(STATIC_DIR, 'styles.css', mimetype='text/css')

@app.route('/app.js')
def serve_js():
    return send_from_directory(STATIC_DIR, 'app.js', mimetype='text/javascript')

# --- API ENDPOINTS ---

@app.route('/api/import/ledgers', methods=['GET'])
def api_import_ledgers():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM tally_import ORDER BY tally_group ASC, ledger_name ASC;")
    rows = [dict(r) for r in cursor.fetchall()]
    conn.close()
    return jsonify(rows)

@app.route('/api/company', methods=['GET', 'POST'])
def api_company():
    conn = get_connection()
    cursor = conn.cursor()
    if request.method == 'POST':
        data = request.json
        cursor.execute("""
        UPDATE company_settings SET
            company_name = ?,
            financial_statement_type = ?,
            financial_year = ?,
            comparative_year = ?,
            currency = ?,
            rounding_unit = ?,
            decimal_places = ?,
            entity_type = ?,
            sector_requirements = ?,
            cin = ?,
            registered_address = ?
        WHERE id = (SELECT MAX(id) FROM company_settings);
        """, (
            data.get('company_name'),
            data.get('financial_statement_type'),
            data.get('financial_year'),
            data.get('comparative_year'),
            data.get('currency'),
            data.get('rounding_unit'),
            data.get('decimal_places', 2),
            data.get('entity_type'),
            data.get('sector_requirements'),
            data.get('cin'),
            data.get('registered_address')
        ))
        conn.commit()
        conn.close()
        log_audit("UPDATE_COMPANY_SETTINGS", "company_settings", details="Updated company profile and statutory parameters")
        return jsonify({'status': 'success', 'message': 'Company settings updated successfully'})
    else:
        profile = get_company_profile()
        conn.close()
        return jsonify(profile)

@app.route('/api/import/sample', methods=['POST'])
def api_import_sample():
    ledgers = load_sample_trial_balance()
    mapped, reviews = execute_auto_mapping()
    return jsonify({
        'status': 'success',
        'message': f'Loaded sample trial balance with {len(ledgers)} ledgers. Auto-mapped {mapped} items ({reviews} require CA Review).',
        'ledger_count': len(ledgers)
    })

@app.route('/api/import/upload', methods=['POST'])
def api_import_upload():
    if 'file' not in request.files:
        return jsonify({'status': 'error', 'message': 'No file uploaded'}), 400
    file = request.files['file']
    filename = file.filename
    ext = filename.split('.')[-1].lower()

    file_bytes = file.read()
    ledgers = []
    parser_used = ''

    try:
        if ext in ['xlsx', 'xls']:
            # ── Auto-detect TB format ─────────────────────────────────────────
            # Raw Tally TB (exported directly from Tally) has no explicit
            # "Parent Group" column.  It uses bold rows for group headers and
            # indentation for hierarchy.  convert_tally_excel() handles this
            # via openpyxl bold + indent detection, correctly skipping group
            # summary rows and only importing actual ledger rows.
            #
            # App-format files (generated by this tool's Tally Converter) DO
            # have a "Parent Tally Group" column.  parse_tally_excel() reads
            # that column directly and imports all data rows as ledgers (the
            # group separator rows starting with '—' are already skipped).
            import pandas as pd, io as _io
            try:
                df_peek = pd.read_excel(_io.BytesIO(file_bytes), nrows=0)
                cols_lower = [str(c).strip().lower() for c in df_peek.columns]
                has_group_col = any('group' in c or 'parent' in c for c in cols_lower)
            except Exception:
                has_group_col = False

            if has_group_col:
                # App-format or custom format with explicit group column
                ledgers = parse_tally_excel(file_bytes)
                parser_used = 'flat-format parser'
            else:
                # Raw Tally TB — use the converter that handles bold/indent groups
                ledgers, _stats, conv_errors = convert_tally_excel(file_bytes)
                parser_used = 'Tally-converter parser (bold/indent detection)'
                if not ledgers:
                    # Converter returned nothing — fall back to simple parser
                    ledgers = parse_tally_excel(file_bytes)
                    parser_used += ' → fallback flat-format parser'
                    if conv_errors:
                        import logging
                        logging.warning("Tally Converter errors: %s", conv_errors)

        elif ext == 'csv':
            ledgers = parse_tally_csv(file_bytes)
            parser_used = 'CSV parser'
        elif ext == 'xml':
            ledgers = parse_tally_xml(file_bytes)
            parser_used = 'XML parser'
        else:
            return jsonify({'status': 'error', 'message': f'Unsupported file format .{ext}'}), 400

        save_imported_ledgers(ledgers, source_filename=filename)
        mapped, reviews = execute_auto_mapping()

        return jsonify({
            'status': 'success',
            'message': (
                f'Successfully imported {len(ledgers)} ledgers from "{filename}" '
                f'using {parser_used}. '
                f'Auto-mapped {mapped} ledgers ({reviews} require CA review).'
            ),
            'count': len(ledgers)
        })
    except Exception as e:
        import traceback
        return jsonify({'status': 'error', 'message': f'Failed to parse file: {str(e)}', 'detail': traceback.format_exc()}), 500


@app.route('/api/mapping/register', methods=['GET'])
def api_mapping_register():
    status_filter = request.args.get('status')
    rows = get_mapping_register(filter_status=status_filter)
    return jsonify(rows)

@app.route('/api/mapping/auto', methods=['POST'])
def api_mapping_auto():
    mapped, reviews = execute_auto_mapping()
    return jsonify({
        'status': 'success',
        'message': f'Auto-mapped {mapped} ledgers ({reviews} marked for CA Review)'
    })

@app.route('/api/mapping/update', methods=['POST'])
def api_mapping_update():
    data = request.json
    ledger_name = data.get('ledger_name')
    schedule3_code = data.get('schedule3_code')
    note_no = data.get('note_no')
    classification = data.get('classification', 'Default')
    cash_flow = data.get('cash_flow_category')
    review_status = data.get('review_status', 'Approved')
    review_note = data.get('review_note', 'User manual override')

    update_single_mapping(ledger_name, schedule3_code, note_no, classification, cash_flow, review_status, review_note)
    return jsonify({'status': 'success', 'message': f'Updated mapping for {ledger_name}'})

@app.route('/api/mapping/bulk', methods=['POST'])
def api_mapping_bulk():
    data = request.json
    tally_group = data.get('tally_group')
    schedule3_code = data.get('schedule3_code')
    note_no = data.get('note_no')
    classification = data.get('classification', 'Current')
    cash_flow = data.get('cash_flow_category', 'Operating')

    count = bulk_map_tally_group(tally_group, schedule3_code, note_no, classification, cash_flow)
    return jsonify({'status': 'success', 'message': f'Bulk mapped {count} ledgers under group {tally_group}'})

@app.route('/api/reconciliation', methods=['GET'])
def api_reconciliation():
    recon_data = run_reconciliation_check()
    return jsonify(recon_data)

@app.route('/api/disclosures/update', methods=['POST'])
def api_disclosures_update():
    data = request.json or {}
    ref_id = data.get('ref_id')
    item_title = data.get('item_title', '')
    status = data.get('status', 'Requires Input')
    details_text = data.get('details_text', '')
    user_name = data.get('user_name', 'CA User')

    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT company_name FROM company_settings ORDER BY id DESC LIMIT 1;")
    c_row = cursor.fetchone()
    company_name = c_row[0] if c_row else 'Apex Engineering India Private Limited'

    cursor.execute("""
    INSERT INTO company_disclosures_checklist (company_name, ref_id, item_title, status, details_text, updated_by, updated_at)
    VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
    ON CONFLICT(company_name, ref_id) DO UPDATE SET
        item_title = excluded.item_title,
        status = excluded.status,
        details_text = excluded.details_text,
        updated_by = excluded.updated_by,
        updated_at = CURRENT_TIMESTAMP;
    """, (company_name, ref_id, item_title, status, details_text, user_name))

    conn.commit()
    conn.close()

    log_audit("UPDATE_DISCLOSURE", "company_disclosures_checklist", target_id=f"{company_name}::{ref_id}", details=f"Updated status to '{status}' for {ref_id}", user_name=user_name)
    return jsonify({'status': 'success', 'message': f'Updated disclosure checklist item {ref_id}'})

@app.route('/api/statements', methods=['GET'])
def api_statements():
    statements = generate_financial_statements()
    return jsonify(statements)

@app.route('/api/notes', methods=['GET'])
def api_notes():
    notes_data = generate_notes()
    return jsonify(notes_data)

@app.route('/api/notes/custom', methods=['GET'])
def api_notes_custom():
    note_no = request.args.get('note_no', '1')
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT company_name FROM company_settings ORDER BY id DESC LIMIT 1;")
    c_row = cursor.fetchone()
    company_name = c_row[0] if c_row else 'Apex Engineering India Private Limited'

    cursor.execute("SELECT custom_content_json FROM company_notes_custom WHERE company_name = ? AND note_no = ?;", (company_name, note_no))
    row = cursor.fetchone()
    conn.close()

    if row and row['custom_content_json']:
        try:
            sections = json.loads(row['custom_content_json'])
            return jsonify({'status': 'success', 'is_custom': True, 'sections': sections})
        except Exception:
            pass

    all_notes = generate_notes()
    for n in all_notes.get('notes', []):
        if n['note_no'] == note_no:
            return jsonify({'status': 'success', 'is_custom': False, 'sections': n.get('sections', [])})
            
    return jsonify({'status': 'error', 'message': f'Note {note_no} not found'}), 404

@app.route('/api/notes/custom/update', methods=['POST'])
def api_notes_custom_update():
    data = request.json or {}
    note_no = str(data.get('note_no', '1'))
    sections = data.get('sections', [])
    user_name = data.get('user_name', 'CA User')

    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT company_name FROM company_settings ORDER BY id DESC LIMIT 1;")
    c_row = cursor.fetchone()
    company_name = c_row[0] if c_row else 'Apex Engineering India Private Limited'

    sections_json = json.dumps(sections)

    cursor.execute("""
    INSERT INTO company_notes_custom (company_name, note_no, custom_content_json, updated_by, updated_at)
    VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
    ON CONFLICT(company_name, note_no) DO UPDATE SET
        custom_content_json = excluded.custom_content_json,
        updated_by = excluded.updated_by,
        updated_at = CURRENT_TIMESTAMP;
    """, (company_name, note_no, sections_json, user_name))

    conn.commit()
    conn.close()

    log_audit("UPDATE_NOTE_POLICIES", "company_notes_custom", target_id=f"{company_name}::Note_{note_no}", details=f"Saved custom accounting policies for Note {note_no} with {len(sections)} sections", user_name=user_name)
    return jsonify({'status': 'success', 'message': f'Updated Note {note_no} policies successfully'})

@app.route('/api/notes/custom/reset', methods=['POST'])
def api_notes_custom_reset():
    data = request.json or {}
    note_no = str(data.get('note_no', '1'))
    user_name = data.get('user_name', 'CA User')

    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT company_name FROM company_settings ORDER BY id DESC LIMIT 1;")
    c_row = cursor.fetchone()
    company_name = c_row[0] if c_row else 'Apex Engineering India Private Limited'

    cursor.execute("DELETE FROM company_notes_custom WHERE company_name = ? AND note_no = ?;", (company_name, note_no))
    conn.commit()
    conn.close()

    log_audit("RESET_NOTE_POLICIES", "company_notes_custom", target_id=f"{company_name}::Note_{note_no}", details=f"Reset Note {note_no} to default template", user_name=user_name)
    return jsonify({'status': 'success', 'message': f'Reset Note {note_no} to default template'})

@app.route('/api/notes/remarks/update', methods=['POST'])
def api_notes_remarks_update():
    data = request.json or {}
    note_no = str(data.get('note_no', '')).strip()
    additional_remarks = data.get('additional_remarks', '').strip()
    user_name = data.get('user_name', 'CA User')

    if not note_no:
        return jsonify({'status': 'error', 'message': 'note_no is required'}), 400

    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT company_name FROM company_settings ORDER BY id DESC LIMIT 1;")
    c_row = cursor.fetchone()
    company_name = c_row[0] if c_row else 'Apex Engineering India Private Limited'

    cursor.execute("""
    INSERT INTO company_note_remarks (company_name, note_no, additional_remarks, updated_by, updated_at)
    VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
    ON CONFLICT(company_name, note_no) DO UPDATE SET
        additional_remarks = excluded.additional_remarks,
        updated_by = excluded.updated_by,
        updated_at = CURRENT_TIMESTAMP;
    """, (company_name, note_no, additional_remarks, user_name))

    conn.commit()
    conn.close()

    log_audit("UPDATE_NOTE_REMARKS", "company_note_remarks", target_id=f"{company_name}::Note_{note_no}", details=f"Saved additional remarks for Note {note_no}", user_name=user_name)
    return jsonify({'status': 'success', 'message': f'Additional remarks saved for Note {note_no}'})

@app.route('/api/notes/review/toggle', methods=['POST'])
def api_notes_review_toggle():
    data = request.json or {}
    note_no = str(data.get('note_no', '')).strip()
    status = data.get('status', 'Approved').strip() # 'Approved' or 'Pending'
    review_notes = data.get('review_notes', '').strip()
    reviewer_name = data.get('reviewer_name', 'CA Lead Auditor').strip()

    if not note_no:
        return jsonify({'status': 'error', 'message': 'note_no is required'}), 400

    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT company_name FROM company_settings ORDER BY id DESC LIMIT 1;")
    c_row = cursor.fetchone()
    company_name = c_row[0] if c_row else 'Apex Engineering India Private Limited'

    cursor.execute("""
    INSERT INTO company_note_reviews (company_name, note_no, review_status, reviewed_by, review_notes, reviewed_at)
    VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
    ON CONFLICT(company_name, note_no) DO UPDATE SET
        review_status = excluded.review_status,
        reviewed_by = excluded.reviewed_by,
        review_notes = excluded.review_notes,
        reviewed_at = CURRENT_TIMESTAMP;
    """, (company_name, note_no, status, reviewer_name, review_notes))

    conn.commit()
    conn.close()

    log_audit("TOGGLE_NOTE_REVIEW", "company_note_reviews", target_id=f"{company_name}::Note_{note_no}", details=f"Note {note_no} marked as {status} by {reviewer_name}", user_name=reviewer_name)
    return jsonify({
        'status': 'success',
        'note_no': note_no,
        'review_status': status,
        'reviewed_by': reviewer_name,
        'message': f'Note {note_no} marked as {status} successfully!'
    })



@app.route('/api/schedule3/master', methods=['GET'])
def api_schedule3_master():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
    SELECT code, code_alias, line_item_name, note_no, normal_balance, default_classification, cash_flow_category, major_head, sub_head
    FROM schedule3_master
    ORDER BY major_head ASC, sub_head ASC, line_item_name ASC;
    """)
    rows = [dict(r) for r in cursor.fetchall()]
    conn.close()
    return jsonify(rows)


@app.route('/api/export/<fmt>', methods=['GET'])
def api_export(fmt):
    downloads_dir = os.path.join(BASE_DIR, "exports")
    os.makedirs(downloads_dir, exist_ok=True)

    if fmt == 'excel':
        filepath = os.path.join(downloads_dir, "Schedule_III_Working_Papers.xlsx")
        export_excel_working_papers(filepath)
        return send_file(filepath, as_attachment=True, download_name="Schedule_III_Working_Papers.xlsx")
    elif fmt == 'word':
        filepath = os.path.join(downloads_dir, "Schedule_III_Draft_Financials.docx")
        export_word_draft(filepath)
        return send_file(filepath, as_attachment=True, download_name="Schedule_III_Draft_Financials.docx")
    elif fmt == 'pdf':
        filepath = os.path.join(downloads_dir, "Schedule_III_Financial_Report.pdf")
        export_pdf_report(filepath)
        return send_file(filepath, as_attachment=True, download_name="Schedule_III_Financial_Report.pdf")
    elif fmt == 'sample_template':
        filepath = os.path.join(TEMPLATES_DIR, "sample_tally_tb.xlsx")
        generate_sample_excel_file(filepath)
        return send_file(filepath, as_attachment=True, download_name="sample_tally_tb.xlsx")
    else:
        return jsonify({'status': 'error', 'message': 'Unknown export format'}), 400

@app.route('/api/backup', methods=['POST'])
def api_backup():
    path = backup_db()
    return jsonify({'status': 'success', 'message': f'Backup saved successfully to {path}'})

@app.route('/api/run_tests', methods=['GET'])
def api_run_tests():
    # Run test suite dynamically
    loader = unittest.TestLoader()
    suite = loader.discover(os.path.join(BASE_DIR, "tests"))
    stream = io.StringIO()
    runner = unittest.TextTestRunner(stream=stream, verbosity=2)
    result = runner.run(suite)
    
    return jsonify({
        'status': 'success' if result.wasSuccessful() else 'failure',
        'tests_run': result.testsRun,
        'failures': len(result.failures),
        'errors': len(result.errors),
        'log': stream.getvalue()
    })

# ── Tally TB Converter Endpoints ──────────────────────────────────────────────

@app.route('/api/tally-converter/preview', methods=['POST'])
def api_tally_converter_preview():
    """
    POST a Tally TB Excel/CSV file; returns a JSON preview of parsed ledgers.
    Supports multipart file upload (field name: 'file').
    """
    if 'file' not in request.files:
        return jsonify({'status': 'error', 'message': 'No file uploaded'}), 400
    file = request.files['file']
    filename = file.filename or ''
    ext = filename.rsplit('.', 1)[-1].lower() if '.' in filename else ''
    file_bytes = file.read()

    if ext in ('xlsx', 'xls'):
        ledgers, stats, errors = convert_tally_excel(file_bytes)
    elif ext == 'csv':
        ledgers, stats, errors = convert_tally_csv(file_bytes)
    else:
        return jsonify({'status': 'error', 'message': f'Unsupported format .{ext}. Please upload .xlsx, .xls or .csv'}), 400

    if errors and not ledgers:
        return jsonify({'status': 'error', 'message': errors[0], 'errors': errors}), 422

    # Serialize a preview (max 200 rows for the table, full for download)
    preview = []
    for l in ledgers:
        opening = l['opening_dr'] - l['opening_cr']
        closing = l['closing_net']
        preview.append({
            'ledger_name'  : l['ledger_name'],
            'tally_group'  : l['tally_group'],
            'opening'      : f"{abs(opening):,.2f} {'Dr' if opening >= 0 else 'Cr'}",
            'debit'        : f"{l['debit']:,.2f}",
            'credit'       : f"{l['credit']:,.2f}",
            'closing'      : f"{abs(closing):,.2f} {'Dr' if closing >= 0 else 'Cr'}",
        })

    return jsonify({
        'status'  : 'success',
        'stats'   : stats,
        'errors'  : errors,
        'preview' : preview,
        'message' : f"Parsed {stats.get('total_ledgers',0)} ledgers from {filename} ({stats.get('groups_detected',0)} Tally groups detected)."
    })


@app.route('/api/tally-converter/download', methods=['POST'])
def api_tally_converter_download():
    """
    POST a Tally TB file; returns the converted Excel in application import format.
    Supports multipart file upload (field name: 'file').
    Optional: import_after=true will also save to DB and run auto-mapping.
    """
    if 'file' not in request.files:
        return jsonify({'status': 'error', 'message': 'No file uploaded'}), 400
    file = request.files['file']
    filename = file.filename or 'tally_tb'
    ext = filename.rsplit('.', 1)[-1].lower() if '.' in filename else ''
    file_bytes = file.read()

    if ext in ('xlsx', 'xls'):
        ledgers, stats, errors = convert_tally_excel(file_bytes)
    elif ext == 'csv':
        ledgers, stats, errors = convert_tally_csv(file_bytes)
    else:
        return jsonify({'status': 'error', 'message': f'Unsupported format .{ext}'}), 400

    if errors and not ledgers:
        return jsonify({'status': 'error', 'message': errors[0]}), 422

    # Generate output Excel
    buf = generate_app_format_excel(ledgers)
    out_name = f"Converted_AppFormat_{filename.rsplit('.', 1)[0]}.xlsx"
    return send_file(
        buf,
        as_attachment=True,
        download_name=out_name,
        mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )


@app.route('/api/tally-converter/import', methods=['POST'])
def api_tally_converter_import():
    """
    POST a Tally TB file; converts and directly imports into the application DB.
    Runs auto-mapping afterwards. Returns import stats.
    """
    if 'file' not in request.files:
        return jsonify({'status': 'error', 'message': 'No file uploaded'}), 400
    file = request.files['file']
    filename = file.filename or 'tally_tb'
    ext = filename.rsplit('.', 1)[-1].lower() if '.' in filename else ''
    file_bytes = file.read()

    if ext in ('xlsx', 'xls'):
        ledgers, stats, errors = convert_tally_excel(file_bytes)
    elif ext == 'csv':
        ledgers, stats, errors = convert_tally_csv(file_bytes)
    else:
        return jsonify({'status': 'error', 'message': f'Unsupported format .{ext}'}), 400

    if errors and not ledgers:
        return jsonify({'status': 'error', 'message': errors[0]}), 422

    # Save to DB and run auto-mapping
    from src.import_engine import save_imported_ledgers
    save_imported_ledgers(ledgers, source_filename=f"[Converted] {filename}")
    mapped, reviews = execute_auto_mapping()

    return jsonify({
        'status'  : 'success',
        'message' : (
            f"Successfully converted and imported {stats.get('total_ledgers',0)} ledgers from '{filename}'. "
            f"Auto-mapped {mapped} ledgers ({reviews} require CA Review)."
        ),
        'stats'   : stats,
        'mapped'  : mapped,
        'reviews' : reviews,
        'errors'  : errors
    })


def run_flask():
    app.run(host='0.0.0.0', port=5000, debug=False, use_reloader=False)

if __name__ == '__main__':
    # Detect actual network IP
    import socket
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        local_ip = s.getsockname()[0]
        s.close()
    except Exception:
        local_ip = "127.0.0.1"

    local_url = 'http://127.0.0.1:5000'
    network_url = f'http://{local_ip}:5000'

    print("="*60)
    print(" Non Ind AS Schedule III Financial Statements Builder")
    print("="*60)
    print(f"  Local URL    : {local_url}")
    print(f"  Network URL  : {network_url}")
    print("="*60)
    webbrowser.open(local_url)

    # Try PyQt6 launcher window; fall back to blocking Flask in main thread
    try:
        from PyQt6.QtWidgets import QApplication, QMainWindow, QLabel, QVBoxLayout, QWidget, QPushButton
        # Run Flask in background thread, Qt in main thread
        threading.Thread(target=run_flask, daemon=True).start()

        qt_app = QApplication(sys.argv)
        window = QMainWindow()
        window.setWindowTitle("Non Ind AS Schedule III Financial Statements Builder")
        window.setGeometry(100, 100, 1100, 750)

        widget = QWidget()
        layout = QVBoxLayout()
        label = QLabel(
            f"Non Ind AS Schedule III Financial Statements Builder\n\n"
            f"Local URL  (this PC):   {local_url}\n"
            f"Network URL (LAN):      {network_url}\n\n"
            f"Share the Network URL with other devices on the same Wi-Fi/LAN."
        )
        label.setStyleSheet("font-size: 15px; color: #1F497D; font-weight: bold; margin: 20px;")

        btn_local = QPushButton("Open on This PC")
        btn_local.setStyleSheet("font-size: 14px; padding: 12px; background-color: #1F497D; color: white; border-radius: 6px; font-weight: bold;")
        btn_local.clicked.connect(lambda: webbrowser.open(local_url))

        btn_network = QPushButton(f"Open Network URL: {network_url}")
        btn_network.setStyleSheet("font-size: 13px; padding: 10px; background-color: #16a34a; color: white; border-radius: 6px; font-weight: bold;")
        btn_network.clicked.connect(lambda: webbrowser.open(network_url))

        layout.addWidget(label)
        layout.addWidget(btn_local)
        layout.addWidget(btn_network)
        widget.setLayout(layout)
        window.setCentralWidget(widget)
        window.show()
        sys.exit(qt_app.exec())
    except Exception as e:
        # PyQt6 not available — run Flask in main thread (keeps process alive)
        print(f"PyQt6 not available ({e}). Running Flask server. Access at {local_url} or {network_url}")
        run_flask()
