import pandas as pd
import xml.etree.ElementTree as ET
import openpyxl
import csv
import io
import os
import sqlite3
from src.db import get_connection, log_audit

def parse_tally_excel(file_path_or_bytes):
    """
    Parses Tally export Excel files.
    Tally exported Excel files usually have columns like:
    Ledger Name, Group/Parent, Opening Balance, Debit, Credit, Closing Balance
    or Opening Dr/Cr, Closing Dr/Cr.
    """
    # pandas read_excel requires a file path or file-like object, not raw bytes
    if isinstance(file_path_or_bytes, bytes):
        file_path_or_bytes = io.BytesIO(file_path_or_bytes)
    df = pd.read_excel(file_path_or_bytes, skiprows=0)
    # Clean header names
    df.columns = [str(c).strip() for c in df.columns]
    
    ledgers = []
    
    # Flexible column matching
    col_map = {}
    for col in df.columns:
        clow = col.lower()
        if 'ledger' in clow or 'particular' in clow or 'account' in clow or 'name' in clow:
            col_map['ledger'] = col
        elif 'group' in clow or 'parent' in clow or 'category' in clow:
            col_map['group'] = col
        elif 'open' in clow:
            col_map['opening'] = col
        elif 'debit' in clow or 'dr' in clow and 'close' not in clow and 'open' not in clow:
            col_map['debit'] = col
        elif 'credit' in clow or 'cr' in clow and 'close' not in clow and 'open' not in clow:
            col_map['credit'] = col
        elif 'close' in clow or 'closing' in clow:
            col_map['closing'] = col
        elif 'prior' in clow or 'comparative' in clow or 'py' in clow or 'prev' in clow:
            col_map['prior'] = col

    # Fallbacks if columns are positional
    if 'ledger' not in col_map and len(df.columns) > 0:
        col_map['ledger'] = df.columns[0]
    if 'group' not in col_map and len(df.columns) > 1:
        col_map['group'] = df.columns[1]

    current_group = "Primary"
    seen_names = set()   # deduplicate by ledger name
    for idx, row in df.iterrows():
        ledger_name = str(row.get(col_map.get('ledger', df.columns[0]), '')).strip()

        # Skip blank / header / total rows
        if not ledger_name or ledger_name.lower() in ['total', 'grand total', 'nan', 'none', 'particulars', 'ledger name']:
            continue
        # Skip group-separator rows generated by the Tally Converter (e.g. '— Capital Account —')
        if ledger_name.startswith('—') or ledger_name.startswith('---') or ledger_name.startswith('–'):
            continue
        # Deduplicate: keep first occurrence
        if ledger_name in seen_names:
            continue
        seen_names.add(ledger_name)
            
        group_name = str(row.get(col_map.get('group', ''), '')).strip()
        if not group_name or group_name.lower() == 'nan':
            # Check if this row is a group header in Tally single column export
            group_name = current_group
        else:
            current_group = group_name

        def safe_float(val):
            """Parse amount, returning signed float (Cr suffix → negative)."""
            if pd.isna(val) or val is None: return 0.0
            val_str = str(val).replace(',', '').strip()
            # Handle Tally Dr/Cr suffixes like "150000 Dr" or "50000 Cr"
            is_cr = 'cr' in val_str.lower()
            val_str = val_str.lower().replace('dr', '').replace('cr', '').strip()
            try:
                num = float(val_str)
                return -num if is_cr else num
            except:
                return 0.0

        def has_sign(key):
            """Return True if the cell for this key has an explicit Dr/Cr suffix."""
            col_name = col_map.get(key)
            if not col_name or col_name not in row:
                return False
            raw = str(row[col_name]).strip().lower()
            return raw.endswith('dr') or raw.endswith('cr')

        def safe_get(key):
            col_name = col_map.get(key)
            if not col_name or col_name not in row:
                return 0.0
            return safe_float(row[col_name])

        opening_val = safe_get('opening')
        debit_val   = abs(safe_get('debit'))
        credit_val  = abs(safe_get('credit'))
        prior_val   = safe_get('prior')

        # Determine closing balance with correct sign:
        #   • If the closing cell has an explicit Dr/Cr suffix → trust it directly.
        #   • Otherwise Tally exported a plain unsigned positive number.
        #     Use the fundamental double-entry formula:
        #       closing = opening(signed) + debit(abs) - credit(abs)
        #     This is always sign-correct because:
        #       - opening is signed negative for Cr-normal accounts
        #       - debit/credit are absolute transaction amounts
        if has_sign('closing'):
            closing_val = safe_get('closing')
        else:
            closing_val = opening_val + debit_val - credit_val

        ledgers.append({
            'ledger_name': ledger_name,
            'tally_group': group_name if group_name else 'Unassigned Group',
            'opening_dr': opening_val if opening_val > 0 else 0.0,
            'opening_cr': abs(opening_val) if opening_val < 0 else 0.0,
            'debit': debit_val,
            'credit': credit_val,
            'closing_dr': closing_val if closing_val > 0 else 0.0,
            'closing_cr': abs(closing_val) if closing_val < 0 else 0.0,
            'closing_net': closing_val,
            'prior_closing_net': prior_val
        })

    # ── Strip Tally group-summary rows ──────────────────────────────────────
    ALL_TALLY_GROUPS = {
        'capital account', 'reserves & surplus', 'current liabilities', 'duties & taxes',
        'provisions', 'bank od a/c', 'secured loans', 'unsecured loans',
        'loans (liability)', 'fixed assets', 'investments', 'current assets', 'bank accounts',
        'cash-in-hand', 'deposits (asset)', 'loans & advances (asset)',
        'stock-in-hand', 'sales accounts', 'purchase accounts', 'direct incomes',
        'indirect incomes', 'direct expenses', 'indirect expenses', 'branch / divisions',
        'misc. expenses (asset)', 'suspense a/c', 'primary'
    }
    child_groups = {l['tally_group'].lower() for l in ledgers}
    filtered_ledgers = []
    for l in ledgers:
        name_lower = l['ledger_name'].lower().strip()
        # Drop if it is a known group header or its name appears as a group of other ledgers
        if name_lower in child_groups:
            continue
        if name_lower in ALL_TALLY_GROUPS and name_lower == l['tally_group'].lower().strip():
            continue
        filtered_ledgers.append(l)

    return filtered_ledgers

def parse_tally_csv(file_path_or_bytes):
    """
    Parses Tally CSV export files using pandas read_csv.
    """
    if isinstance(file_path_or_bytes, bytes):
        content = file_path_or_bytes.decode('utf-8-sig', errors='ignore')
        stream = io.StringIO(content)
    elif isinstance(file_path_or_bytes, str):
        stream = open(file_path_or_bytes, encoding='utf-8-sig', errors='ignore')
    else:
        stream = file_path_or_bytes

    df = pd.read_csv(stream)
    df.columns = [str(c).strip() for c in df.columns]

    ledgers = []
    col_map = {}
    for col in df.columns:
        clow = str(col).strip().lower()
        if 'ledger' in clow or 'particular' in clow or 'account' in clow or 'name' in clow:
            if 'ledger' not in col_map: col_map['ledger'] = col
        elif 'group' in clow or 'parent' in clow or 'category' in clow:
            if 'group' not in col_map: col_map['group'] = col
        elif 'open' in clow:
            if 'opening' not in col_map: col_map['opening'] = col
        elif ('debit' in clow or clow == 'dr') and 'close' not in clow and 'open' not in clow:
            if 'debit' not in col_map: col_map['debit'] = col
        elif ('credit' in clow or clow == 'cr') and 'close' not in clow and 'open' not in clow:
            if 'credit' not in col_map: col_map['credit'] = col
        elif 'close' in clow or 'closing' in clow:
            if 'closing' not in col_map: col_map['closing'] = col
        elif 'prior' in clow or 'comparative' in clow or 'py' in clow or 'prev' in clow:
            if 'prior' not in col_map: col_map['prior'] = col

    if 'ledger' not in col_map and len(df.columns) > 0:
        col_map['ledger'] = df.columns[0]
    if 'group' not in col_map and len(df.columns) > 1:
        col_map['group'] = df.columns[1]

    current_group = 'Primary'
    seen_names = set()
    for idx, row in df.iterrows():
        ledger_name = str(row.get(col_map.get('ledger', df.columns[0]), '')).strip()
        if not ledger_name or ledger_name.lower() in ['total', 'grand total', 'nan', 'none', 'particulars', 'ledger name']:
            continue
        if ledger_name.startswith('—') or ledger_name.startswith('---') or ledger_name.startswith('–'):
            continue
        if ledger_name in seen_names:
            continue
        seen_names.add(ledger_name)

        group_name = str(row.get(col_map.get('group', ''), '')).strip()
        if not group_name or group_name.lower() == 'nan':
            group_name = current_group
        else:
            current_group = group_name

        def safe_float(val):
            if pd.isna(val) or val is None: return 0.0
            val_str = str(val).replace(',', '').strip()
            is_cr = 'cr' in val_str.lower()
            val_str = val_str.lower().replace('dr', '').replace('cr', '').strip()
            try:
                num = float(val_str)
                return -num if is_cr else num
            except:
                return 0.0

        def has_sign(key):
            """Return True if the cell for this key has an explicit Dr/Cr suffix."""
            col_name = col_map.get(key)
            if not col_name or col_name not in row:
                return False
            raw = str(row[col_name]).strip().lower()
            return raw.endswith('dr') or raw.endswith('cr')

        def safe_get(key):
            col_name = col_map.get(key)
            if not col_name or col_name not in row:
                return 0.0
            return safe_float(row[col_name])

        opening_val = safe_get('opening')
        debit_val   = abs(safe_get('debit'))
        credit_val  = abs(safe_get('credit'))
        prior_val   = safe_get('prior')

        # Use signed double-entry formula when no explicit Dr/Cr suffix
        if has_sign('closing'):
            closing_val = safe_get('closing')
        else:
            closing_val = opening_val + debit_val - credit_val

        ledgers.append({
            'ledger_name': ledger_name,
            'tally_group': group_name if group_name else 'Unassigned Group',
            'opening_dr': opening_val if opening_val > 0 else 0.0,
            'opening_cr': abs(opening_val) if opening_val < 0 else 0.0,
            'debit': debit_val,
            'credit': credit_val,
            'closing_dr': closing_val if closing_val > 0 else 0.0,
            'closing_cr': abs(closing_val) if closing_val < 0 else 0.0,
            'closing_net': closing_val,
            'prior_closing_net': prior_val
        })

    # Strip group-summary rows (same logic as parse_tally_excel)
    ALL_TALLY_GROUPS = {
        'capital account', 'reserves & surplus', 'current liabilities', 'duties & taxes',
        'provisions', 'bank od a/c', 'secured loans', 'unsecured loans',
        'loans (liability)', 'fixed assets', 'investments', 'current assets', 'bank accounts',
        'cash-in-hand', 'deposits (asset)', 'loans & advances (asset)',
        'stock-in-hand', 'sales accounts', 'purchase accounts', 'direct incomes',
        'indirect incomes', 'direct expenses', 'indirect expenses', 'branch / divisions',
        'misc. expenses (asset)', 'suspense a/c', 'primary'
    }
    child_groups = {l['tally_group'].lower() for l in ledgers}
    filtered_ledgers = []
    for l in ledgers:
        name_lower = l['ledger_name'].lower().strip()
        if name_lower in child_groups:
            continue
        if name_lower in ALL_TALLY_GROUPS and name_lower == l['tally_group'].lower().strip():
            continue
        filtered_ledgers.append(l)

    return filtered_ledgers


def load_sample_trial_balance(industry_type="Manufacturing"):
    # (keeps remainder of file intact)
    pass
# Wait, let's keep save_imported_ledgers intact! Let's target smaller chunk!

def parse_tally_xml(file_path_or_bytes):
    """
    Parses Tally XML exported file (<ENVELOPE><BODY><DATA><TALLYMESSAGE><LEDGER>...)
    """
    # ET.parse requires a file path or file-like object, not raw bytes
    if isinstance(file_path_or_bytes, bytes):
        file_path_or_bytes = io.BytesIO(file_path_or_bytes)
    tree = ET.parse(file_path_or_bytes)
    root = tree.getroot()
    
    ledgers = []
    # Find all LEDGER nodes
    for ledger in root.findall('.//LEDGER'):
        name = ledger.get('NAME') or ledger.findtext('LANGUAGENAME.LIST/NAME.LIST/NAME') or ledger.findtext('NAME')
        if not name:
            continue
        parent = ledger.findtext('PARENT') or 'Primary'
        opening = ledger.findtext('OPENINGBALANCE') or '0'
        closing = ledger.findtext('CLOSINGBALANCE') or '0'
        
        def parse_xml_num(val):
            if not val: return 0.0
            val = val.replace(',', '').strip()
            is_cr = val.endswith('Cr') or val.startswith('-')
            clean_val = val.replace('Dr', '').replace('Cr', '').strip()
            try:
                num = float(clean_val)
                return -num if is_cr else num
            except:
                return 0.0

        op_num = parse_xml_num(opening)
        cl_num = parse_xml_num(closing)

        ledgers.append({
            'ledger_name': name,
            'tally_group': parent,
            'opening_dr': op_num if op_num > 0 else 0.0,
            'opening_cr': abs(op_num) if op_num < 0 else 0.0,
            'debit': 0.0,
            'credit': 0.0,
            'closing_dr': cl_num if cl_num > 0 else 0.0,
            'closing_cr': abs(cl_num) if cl_num < 0 else 0.0,
            'closing_net': cl_num,
            'prior_closing_net': 0.0
        })
    return ledgers

def save_imported_ledgers(ledgers, source_filename="Uploaded_TB"):
    conn = get_connection()
    cursor = conn.cursor()

    # Clear previous import
    cursor.execute("DELETE FROM tally_import;")
    cursor.execute("DELETE FROM ledger_mappings;")

    # Deduplicate by ledger_name (keep last occurrence, which tends to have better amounts)
    seen = {}
    for l in ledgers:
        name = str(l.get('ledger_name', '')).strip()
        if not name:
            continue
        # Skip group-separator rows that leaked in
        if name.startswith('—') or name.startswith('---') or name.startswith('–'):
            continue
        seen[name] = l   # overwrite duplicates

    clean_ledgers = list(seen.values())

    for l in clean_ledgers:
        cursor.execute("""
        INSERT OR REPLACE INTO tally_import
            (ledger_name, tally_group, opening_dr, opening_cr, debit, credit,
             closing_dr, closing_cr, closing_net, prior_closing_net, source_filename)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
        """, (
            l['ledger_name'],
            l['tally_group'],
            l.get('opening_dr', 0.0),
            l.get('opening_cr', 0.0),
            l.get('debit', 0.0),
            l.get('credit', 0.0),
            l.get('closing_dr', 0.0),
            l.get('closing_cr', 0.0),
            l.get('closing_net', 0.0),
            l.get('prior_closing_net', 0.0),
            source_filename
        ))

    conn.commit()
    conn.close()
    log_audit("IMPORT_TB", "tally_import", details=f"Imported {len(clean_ledgers)} ledgers from {source_filename} (deduplicated from {len(ledgers)} rows)")

def load_sample_trial_balance(industry_type="Manufacturing"):
    """
    Generates a complete, mathematically balanced sample trial balance with comparative numbers.
    All figures in INR (Absolute).
    """
    sample_ledgers = [
        # Equity & Capital
        {"ledger_name": "Equity Share Capital (10,00,000 Shares @ Rs 10)", "tally_group": "Capital Account", "closing_net": -10000000.0, "prior_closing_net": -10000000.0},
        {"ledger_name": "Securities Premium Reserve", "tally_group": "Reserves & Surplus", "closing_net": -5000000.0, "prior_closing_net": -5000000.0},
        {"ledger_name": "General Reserve", "tally_group": "Reserves & Surplus", "closing_net": -7500000.0, "prior_closing_net": -6000000.0},
        {"ledger_name": "Retained Earnings / Surplus in P&L", "tally_group": "Reserves & Surplus", "closing_net": -22340000.0, "prior_closing_net": -18500000.0},
        
        # Long Term Borrowings & Liabilities
        {"ledger_name": "Term Loan from HDFC Bank", "tally_group": "Loans (Liability)", "closing_net": -12000000.0, "prior_closing_net": -15000000.0},
        {"ledger_name": "Deferred Tax Liability (Net)", "tally_group": "Duties & Taxes", "closing_net": -1250000.0, "prior_closing_net": -1100000.0},
        {"ledger_name": "Provision for Employee Gratuity (Long Term)", "tally_group": "Provisions", "closing_net": -2200000.0, "prior_closing_net": -1800000.0},

        # Short Term Liabilities & Payables
        {"ledger_name": "Working Capital Overdraft - ICICI Bank", "tally_group": "Bank OD A/c", "closing_net": -4500000.0, "prior_closing_net": -3800000.0},
        {"ledger_name": "Sundry Creditors - MSME Suppliers", "tally_group": "Sundry Creditors", "closing_net": -1800000.0, "prior_closing_net": -1500000.0},
        {"ledger_name": "Sundry Creditors - Trade Suppliers", "tally_group": "Sundry Creditors", "closing_net": -8500000.0, "prior_closing_net": -9200000.0},
        {"ledger_name": "GST Payable Account", "tally_group": "Duties & Taxes", "closing_net": -1400000.0, "prior_closing_net": -1200000.0},
        {"ledger_name": "TDS Payable Account", "tally_group": "Duties & Taxes", "closing_net": -350000.0, "prior_closing_net": -300000.0},
        {"ledger_name": "Outstanding Expenses Payable", "tally_group": "Duties & Taxes", "closing_net": -950000.0, "prior_closing_net": -850000.0},
        {"ledger_name": "Provision for Current Tax FY 23-24", "tally_group": "Provisions", "closing_net": -2800000.0, "prior_closing_net": -2400000.0},

        # Fixed Assets (PPE)
        {"ledger_name": "Factory Building - Gross Block", "tally_group": "Fixed Assets", "closing_net": 25000000.0, "prior_closing_net": 25000000.0},
        {"ledger_name": "Plant & Machinery - Gross Block", "tally_group": "Fixed Assets", "closing_net": 32000000.0, "prior_closing_net": 28000000.0},
        {"ledger_name": "Computers & IT Hardware", "tally_group": "Fixed Assets", "closing_net": 3500000.0, "prior_closing_net": 3000000.0},
        {"ledger_name": "Office Equipment & Furniture", "tally_group": "Fixed Assets", "closing_net": 2800000.0, "prior_closing_net": 2500000.0},
        {"ledger_name": "Accumulated Depreciation - PPE", "tally_group": "Fixed Assets", "closing_net": -12500000.0, "prior_closing_net": -9800000.0},
        {"ledger_name": "Capital Work-in-Progress (Solar Plant)", "tally_group": "Fixed Assets", "closing_net": 4200000.0, "prior_closing_net": 1500000.0},

        # Non-Current Investments & Loans
        {"ledger_name": "Investment in Government Securities", "tally_group": "Investments", "closing_net": 5000000.0, "prior_closing_net": 5000000.0},
        {"ledger_name": "Security Deposits for Electricity & Premises", "tally_group": "Deposits (Asset)", "closing_net": 1800000.0, "prior_closing_net": 1800000.0},

        # Current Assets & Inventories
        {"ledger_name": "Raw Materials Stock", "tally_group": "Stock-in-Hand", "closing_net": 6500000.0, "prior_closing_net": 5800000.0},
        {"ledger_name": "Work-in-Progress Stock", "tally_group": "Stock-in-Hand", "closing_net": 3200000.0, "prior_closing_net": 2900000.0},
        {"ledger_name": "Finished Goods Inventory", "tally_group": "Stock-in-Hand", "closing_net": 5400000.0, "prior_closing_net": 4800000.0},
        {"ledger_name": "Sundry Debtors - Domestic Customers", "tally_group": "Sundry Debtors", "closing_net": 16500000.0, "prior_closing_net": 14200000.0},
        {"ledger_name": "Sundry Debtors - Export Customers", "tally_group": "Sundry Debtors", "closing_net": 4800000.0, "prior_closing_net": 3900000.0},
        {"ledger_name": "Prepaid Insurance & Software Expense", "tally_group": "Deposits (Asset)", "closing_net": 650000.0, "prior_closing_net": 550000.0},
        {"ledger_name": "Advance Tax & TDS Receivable FY 23-24", "tally_group": "Loans & Advances (Asset)", "closing_net": 3100000.0, "prior_closing_net": 2600000.0},

        # Cash & Bank Balances
        {"ledger_name": "State Bank of India - Current A/c", "tally_group": "Bank Accounts", "closing_net": 4200000.0, "prior_closing_net": 3100000.0},
        {"ledger_name": "HDFC Bank - Current A/c", "tally_group": "Bank Accounts", "closing_net": 2800000.0, "prior_closing_net": 1900000.0},
        {"ledger_name": "Cash-in-Hand", "tally_group": "Cash-in-Hand", "closing_net": 140000.0, "prior_closing_net": 120000.0},

        # P&L Revenue & Incomes
        {"ledger_name": "Sale of Manufactured Goods (Domestic)", "tally_group": "Sales Accounts", "closing_net": -92280000.0, "prior_closing_net": -79280000.0},
        {"ledger_name": "Sale of Goods (Export)", "tally_group": "Sales Accounts", "closing_net": -22000000.0, "prior_closing_net": -18000000.0},
        {"ledger_name": "Scrap Sales & Waste Realizations", "tally_group": "Direct Incomes", "closing_net": -1200000.0, "prior_closing_net": -950000.0},
        {"ledger_name": "Interest Received on Fixed Deposits", "tally_group": "Indirect Incomes", "closing_net": -450000.0, "prior_closing_net": -380000.0},
        {"ledger_name": "Foreign Exchange Gain (Net)", "tally_group": "Indirect Incomes", "closing_net": -350000.0, "prior_closing_net": -250000.0},

        # P&L Expenses
        {"ledger_name": "Purchase of Raw Materials", "tally_group": "Purchase Accounts", "closing_net": 48000000.0, "prior_closing_net": 41000000.0},
        {"ledger_name": "Freight & Freight Inward Expense", "tally_group": "Direct Expenses", "closing_net": 2800000.0, "prior_closing_net": 2400000.0},
        {"ledger_name": "Power, Electricity & Fuel Charges", "tally_group": "Direct Expenses", "closing_net": 4500000.0, "prior_closing_net": 3900000.0},
        {"ledger_name": "Salaries, Wages & Bonus Expense", "tally_group": "Indirect Expenses", "closing_net": 18500000.0, "prior_closing_net": 15800000.0},
        {"ledger_name": "PF & ESI Contribution Expense", "tally_group": "Indirect Expenses", "closing_net": 1600000.0, "prior_closing_net": 1400000.0},
        {"ledger_name": "Staff Welfare Expense", "tally_group": "Indirect Expenses", "closing_net": 750000.0, "prior_closing_net": 650000.0},
        {"ledger_name": "Interest Paid on Term Loan & OD", "tally_group": "Indirect Expenses", "closing_net": 1450000.0, "prior_closing_net": 1650000.0},
        {"ledger_name": "Bank Charges & Commission", "tally_group": "Indirect Expenses", "closing_net": 180000.0, "prior_closing_net": 150000.0},
        {"ledger_name": "Depreciation Expense for the Year", "tally_group": "Indirect Expenses", "closing_net": 2700000.0, "prior_closing_net": 2400000.0},
        {"ledger_name": "Factory Maintenance & Repairs", "tally_group": "Indirect Expenses", "closing_net": 1400000.0, "prior_closing_net": 1200000.0},
        {"ledger_name": "Legal, Professional & Audit Fees", "tally_group": "Indirect Expenses", "closing_net": 850000.0, "prior_closing_net": 750000.0},
        {"ledger_name": "Travelling & Conveyance Expense", "tally_group": "Indirect Expenses", "closing_net": 1100000.0, "prior_closing_net": 950000.0},
        {"ledger_name": "CSR Expenditure (Education & Health)", "tally_group": "Indirect Expenses", "closing_net": 400000.0, "prior_closing_net": 350000.0},
        {"ledger_name": "Rates, Taxes & Insurance", "tally_group": "Indirect Expenses", "closing_net": 600000.0, "prior_closing_net": 520000.0},
        {"ledger_name": "Provision for Current Tax Expense", "tally_group": "Indirect Expenses", "closing_net": 2800000.0, "prior_closing_net": 2400000.0},
        {"ledger_name": "Deferred Tax Charge for Year", "tally_group": "Indirect Expenses", "closing_net": 150000.0, "prior_closing_net": 120000.0}
    ]

    formatted_ledgers = []
    for l in sample_ledgers:
        net = l['closing_net']
        prior_net = l['prior_closing_net']
        formatted_ledgers.append({
            'ledger_name': l['ledger_name'],
            'tally_group': l['tally_group'],
            'opening_dr': net if net > 0 else 0.0,
            'opening_cr': abs(net) if net < 0 else 0.0,
            'debit': net if net > 0 else 0.0,
            'credit': abs(net) if net < 0 else 0.0,
            'closing_dr': net if net > 0 else 0.0,
            'closing_cr': abs(net) if net < 0 else 0.0,
            'closing_net': net,
            'prior_closing_net': prior_net
        })

    save_imported_ledgers(formatted_ledgers, source_filename="Sample_Tally_TB_Demo.xlsx")
    return formatted_ledgers

def generate_sample_excel_file(output_path):
    """
    Creates a physical Excel file template sample_tally_tb.xlsx in templates folder.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Tally Trial Balance"
    
    headers = ["Particulars / Ledger Name", "Parent Tally Group", "Opening Balance", "Debit Amount", "Credit Amount", "Closing Balance", "Prior Year Closing Balance"]
    ws.append(headers)

    ledgers = load_sample_trial_balance()
    for l in ledgers:
        net = l['closing_net']
        py_net = l['prior_closing_net']
        ws.append([
            l['ledger_name'],
            l['tally_group'],
            f"{abs(l['opening_dr'] or l['opening_cr'])} {'Dr' if l['opening_dr']>0 else 'Cr'}",
            l['debit'],
            l['credit'],
            f"{abs(net)} {'Dr' if net>0 else 'Cr'}",
            f"{abs(py_net)} {'Dr' if py_net>0 else 'Cr'}"
        ])
        
    wb.save(output_path)
    return output_path
